/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses.PS;

import static F.Datetostringwidthformat.getstringfromdate;
import F.FLaporan;
import static F.JackOptionpane.jackop;
import F.RunMultiUpd;
import F.RunUpd;
import static F.VarJFrame.menuPermintaanKerja;
import static F.VarJFrame.tambahPermintaanKerja;
import static F.VarJFrame.ubahPermintaanKerja;
import static F.Variablebanking.Mechanik;
import static F.Variablebanking.Pimpinan;
import static F.Variablebanking.SUsername;
import static F.Variablebanking.hak;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JACK
 */
public class MPService extends javax.swing.JFrame {

    /**
     * Creates new form JenisService
     */
    public MPService() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle(NamaMaster);
        BTambah.setVisible(hak[19]);
        BUbah.setVisible(hak[20]);
        BHapus.setVisible(hak[21]);
        setVisible(true);
    }

    String NamaMaster = "Permintaan Service";
    String SelecQ = "SELECT `No` as 'NO', `NoPermintaan` as 'NoPermintaan',  DATE_FORMAT(`Tgl`,'%d/%m/%Y %H:%i') as 'Tanggal', `Plat` as 'Plat', `Sopir` as 'Sopir', IF(`JPermintaan` = 0, 'Perawatan',if(`JPermintaan` = 1,'Perbaikan',if(`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as 'Jenis Permintaan', if(`JPekerjaan`=0,'Kecil',if(`JPekerjaan`=1,'Sedang', if(`JPekerjaan`=2,'Besar','Eror'))) as 'Jenis Pekerjaan', if(`TingkatPekerjaan`=0,'Dapat Di Tunda', if(`TingkatPekerjaan`=1,'Darurat','Eror')) as 'Tingkat Pekerjaan', `KMT` as 'KM Truck', `User` as 'User', `CatKhusus` as 'Catatan Khusus',`Print` as 'Print'  FROM `tbpermintaan`";
    String SelecQ2 = "SELECT `No`,`NoPermintaan`,`Tgl`,`Plat`,`Sopir`,IF(`JPermintaan` = 0, 'Perawatan',if(`JPermintaan` = 1,'Perbaikan',if(`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))), if(`JPekerjaan`=0,'Kecil',if(`JPekerjaan`=1,'Sedang', if(`JPekerjaan`=2,'Besar','Eror'))), if(`TingkatPekerjaan`=0,'Dapat Di Tunda', if(`TingkatPekerjaan`=1,'Darurat','Eror')),`KMT`, `User`,`CatKhusus`,`Print` FROM `tbpermintaan`";
    String QInsert;
    String QUpdate;
    String QDelete1;
    String QDelete2;

    void getQDelete() {
        QDelete1 = "DELETE FROM `tbdetailpermintaan` WHERE `NoPermintaan` = '" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'";
        QDelete2 = "DELETE FROM `tbpermintaan` WHERE `NoPermintaan` = '" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'";
    }

    void getSelectedData() {
        int bar = jktable1.getSelectedRow();
    }

    /**
     *
     */
    public void refresh() {
        JTCari.setText("");
        jktable1.tampilkan();
        jktable1.clearSelection();
        jktable1.setQuery(SelecQ + " Order By No Desc limit 100");
        jktable1.tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jScrollPane1 = new javax.swing.JScrollPane();
          jktable1 = new F.Jktable();
          jLabel1 = new javax.swing.JLabel();
          BTambah = new javax.swing.JButton();
          BUbah = new javax.swing.JButton();
          BHapus = new javax.swing.JButton();
          BRefresh = new javax.swing.JButton();
          jcomFromDBtable1 = new F.JcomFromDBtable();
          JTCari = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jktable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String []
               {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jktable1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    jktable1KeyReleased(evt);
               }
          });
          jktable1.setQuery(SelecQ+"order by `No` desc");
          jktable1.tampilkan();
          jScrollPane1.setViewportView(jktable1);
          jktable1.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });

               jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel1.setText("Cari Berdasarkan :");

               BTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BTambah.setText("Tambah");

               org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement == null}"), BTambah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BTambah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BTambahActionPerformed(evt);
                    }
               });
               BTambah.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BTambahKeyReleased(evt);
                    }
               });

               BUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BUbah.setText("Ubah");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BUbah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BUbah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BUbahActionPerformed(evt);
                    }
               });
               BUbah.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BUbahKeyReleased(evt);
                    }
               });

               BHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BHapus.setText("Hapus");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BHapus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BHapus.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BHapusActionPerformed(evt);
                    }
               });
               BHapus.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BHapusKeyReleased(evt);
                    }
               });

               BRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BRefresh.setText("Refresh");
               BRefresh.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BRefreshActionPerformed(evt);
                    }
               });
               BRefresh.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BRefreshKeyReleased(evt);
                    }
               });

               jcomFromDBtable1.setQuery1(SelecQ);
               jcomFromDBtable1.setQuery2(SelecQ2);
               jcomFromDBtable1.excute1();
               jcomFromDBtable1.excute2();
               jcomFromDBtable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jcomFromDBtable1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jcomFromDBtable1ActionPerformed(evt);
                    }
               });
               jcomFromDBtable1.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         jcomFromDBtable1KeyReleased(evt);
                    }
               });

               JTCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               JTCari.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         JTCariKeyReleased(evt);
                    }
               });

               jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jButton1.setText("Print");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               jButton1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jButton1ActionPerformed(evt);
                    }
               });
               jButton1.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         jButton1KeyReleased(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(10, 10, 10)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jScrollPane1)
                              .addGroup(layout.createSequentialGroup()
                                   .addComponent(jLabel1)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 429, Short.MAX_VALUE)
                                   .addComponent(jButton1)
                                   .addGap(6, 6, 6)
                                   .addComponent(BRefresh)
                                   .addGap(6, 6, 6)
                                   .addComponent(BHapus)
                                   .addGap(6, 6, 6)
                                   .addComponent(BUbah)
                                   .addGap(6, 6, 6)
                                   .addComponent(BTambah)))
                         .addContainerGap())
               );
               layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel1)
                                   .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jButton1)
                                   .addComponent(BRefresh)
                                   .addComponent(BHapus)
                                   .addComponent(BUbah)
                                   .addComponent(BTambah)))
                         .addGap(12, 12, 12))
               );

               bindingGroup.bind();

               pack();
          }// </editor-fold>//GEN-END:initComponents

    private void BRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_BRefreshActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        if (tambahPermintaanKerja == null) {
            tambahPermintaanKerja = new TambahPS();
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        if (Proses.PS.Cek.isadaperintahkerja(jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString()) != null) {
            JOptionPane.showMessageDialog(this, "SPK Telah dibuat Tidak Dapat Di Rubah");
        } else if (ubahPermintaanKerja == null) {
            ubahPermintaanKerja = new UbahPS(jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_BUbahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        if (jackop("Apakah Anda Yakin Mau Menghapus Data " + NamaMaster)) {
            String H = jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString();
            getQDelete();
            RunMultiUpd runMultiUpd = new F.RunMultiUpd();
            Vector v = new Vector();
            v.add(QDelete1);
            v.add(QDelete2);
            runMultiUpd.setQuery(v);
            runMultiUpd.seterorm("Gagal Hapus Data " + NamaMaster);
            int no = runMultiUpd.excute();
            if (no != 0) {
                showMessageDialog(this, "Berhasil Hapus Data " + NamaMaster);
                refresh();
                F.History.STambah("Hapus Data " + NamaMaster + " " + H);
            }
        } else {
            showMessageDialog(this, "Batal Menghapus Data " + NamaMaster);
        }
    }//GEN-LAST:event_BHapusActionPerformed

    void FCari() {
        Vector v = jcomFromDBtable1.getcoloumname();
        jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%' order by No desc limit 100");
        jktable1.tampilkan();
    }
    private void jcomFromDBtable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomFromDBtable1ActionPerformed
        FCari();        // TODO add your handling code here:
    }//GEN-LAST:event_jcomFromDBtable1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        menuPermintaanKerja = null;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

     private void JTCariKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTCariKeyReleased
     {//GEN-HEADEREND:event_JTCariKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }
         FCari();       // TODO add your handling code here:
     }//GEN-LAST:event_JTCariKeyReleased

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         hashs.put("Title", "SURAT PERMINTAAN SERVICE");
         hashs.put("NoPermintaanKerja", jktable1.getValueAt(jktable1.getSelectedRow(), 1));
         hashs.put("KaMekanik", Mechanik);
         hashs.put("Pimpinan", Pimpinan);
         hashs.put("PrintedBy", "Di Print Oleh " + SUsername + " Pada " + getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("PermintaanKerja");
         fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
         fLaporan.excute();
         RunUpd runUpd = new RunUpd();
         runUpd.setQuery("UPDATE `tbpermintaan` SET `Print`='Yes' WHERE `NoPermintaan`='" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'");
         runUpd.excute();
         F.VarJFrame.menuPermintaanKerja.refresh();
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jktable1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jktable1KeyReleased
     {//GEN-HEADEREND:event_jktable1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }// TODO add your handling code here:
     }//GEN-LAST:event_jktable1KeyReleased

     private void jcomFromDBtable1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcomFromDBtable1KeyReleased
     {//GEN-HEADEREND:event_jcomFromDBtable1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jcomFromDBtable1KeyReleased

     private void jButton1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButton1KeyReleased
     {//GEN-HEADEREND:event_jButton1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jButton1KeyReleased

     private void BRefreshKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BRefreshKeyReleased
     {//GEN-HEADEREND:event_BRefreshKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BRefreshKeyReleased

     private void BHapusKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BHapusKeyReleased
     {//GEN-HEADEREND:event_BHapusKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BHapusKeyReleased

     private void BUbahKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BUbahKeyReleased
     {//GEN-HEADEREND:event_BUbahKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BUbahKeyReleased

     private void BTambahKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BTambahKeyReleased
     {//GEN-HEADEREND:event_BTambahKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BTambahKeyReleased

    /**
     * @param args the command line arguments
     */
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BHapus;
     private javax.swing.JButton BRefresh;
     private javax.swing.JButton BTambah;
     private javax.swing.JButton BUbah;
     private javax.swing.JTextField JTCari;
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JScrollPane jScrollPane1;
     private F.JcomFromDBtable jcomFromDBtable1;
     private F.Jktable jktable1;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(MPService.class.getName());

}
