/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses.PS;

import static F.Datetostringwidthformat.getstringfromdate;
import F.FLaporan;
import F.Jktable;
import F.RunMultiUpd;
import F.RunSelct;
import F.RunSelctOne;
import F.RunUpd;
import static F.VarJFrame.tambahPermintaanKerja;
import static F.Variablebanking.Mechanik;
import static F.Variablebanking.Pimpinan;
import static F.Variablebanking.SUsername;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JACK
 */
public class TambahPS extends javax.swing.JFrame {

    /**
     * Creates new form Serivice
     */
    public TambahPS() {
        initComponents();
        setTitle("Tambah Permintaan Service");
        setLocationRelativeTo(null);
        GetJcomPlat(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
    }
    String QJcP1 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=2 order by `NoCol`";
    String QJcP2 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=3 order by `NoCol`";
    String QJcP3 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=4 order by `NoCol`";
// Code here

    private void GetJcomPlat(String Cari) {
        JcPlat.setQuery("SELECT `NoPolisi` FROM `ttruck` where `NoPolisi` like '%" + Cari + "%' ");
        JcPlat.excute();
    }

    void setKMfromPlat(Object Plat) {
        ////system.out.printlnln(("KMO"));
        RunSelct runSelct = new F.RunSelct();
        try {
            runSelct.setQuery("SELECT `KMO` FROM `ttruck` WHERE `NoPolisi`='" + Plat + "' limit 1");
            ResultSet rs = runSelct.excute();
            if (!rs.isBeforeFirst()) {
                JcKMO.setText("0");
            }
            while (rs.next()) {
                JcKMO.setText(rs.getString("KMO"));
                ////system.out.printlnln(rs.getString("KMO"));
            }
        } catch (SQLException e) {
        } finally {
            runSelct.closecon();
        }
    }

    void getSelectedData() {
        if (JTable.getSelectedRow() != -1) {
            int row = JTable.getSelectedRow();
            JCjenis.setSelectedItem(JTable.getValueAt(row, 1));
            JTKet.setText(JTable.getValueAt(row, 2).toString());
            JTBiaya.setInt(Integer.parseInt(JTable.getValueAt(row, 3).toString()));
        }
    }

    /**
     *
     * @param table
     * @return
     */
    public Object[][] getTableData(Jktable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = dtm.getValueAt(i, j);
            }
        }
        return tableData;
    }

    void RefreshsJtable() {
        JTable.clearSelection();
        JCjenis.setSelectedIndex(0);
        JTKet.setText("");
        JTBiaya.setInt(0);
        jtCPlat.setText("");
    }

    void setenabdisabtextkm() {
        if (!"".equals(JcPlat.getSelectedItem().toString())) {
            RunSelctOne runSelctOne = new F.RunSelctOne();
            runSelctOne.setQuery("SELECT `Stat` FROM `ttruck` WHERE `NoPolisi`= '" + JcPlat.getSelectedItem() + "'");
            String x = runSelctOne.excute();
            if (x.equals("1")) {
                JTKMMobil.setEnabled(false);
            } else {
                JTKMMobil.setEnabled(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          JdTGL = new com.toedter.calendar.JDateChooser();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jLabel14 = new javax.swing.JLabel();
          jLabel16 = new javax.swing.JLabel();
          jButton1 = new javax.swing.JButton();
          jLabel17 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          jLabel21 = new javax.swing.JLabel();
          jLabel22 = new javax.swing.JLabel();
          jLabel23 = new javax.swing.JLabel();
          jLabel24 = new javax.swing.JLabel();
          JcPlat = new F.JcomFromDb();
          JCjenis = new F.JcomFromDb();
          JTCari = new F.JackTextField();
          jLabel5 = new javax.swing.JLabel();
          JcKMO = new F.JNumberTextField();
          JcPemintaan = new F.JcomFromDb();
          JcPerbaikan = new F.JcomFromDb();
          JcPrioritas = new F.JcomFromDb();
          BtnUbah = new javax.swing.JButton();
          BtnRefresh = new javax.swing.JButton();
          JTBiaya = new F.RibuanTextField();
          JTKMMobil = new F.RibuanTextField();
          JtNoPermintaan = new F.JackTextField();
          JtSopir = new F.JackTextField();
          jtCPlat = new F.JackTextField();
          jtUser = new F.JackTextField();
          JTKet = new F.JackTextField();
          JTTime = new javax.swing.JFormattedTextField();
          JTCatKhusus = new F.JackTextField();
          jLabel25 = new javax.swing.JLabel();
          jScrollPane1 = new javax.swing.JScrollPane();
          JTable = new F.Jktable();
          BtnTambah = new javax.swing.JButton();
          BtnHapus = new javax.swing.JButton();
          jButton2 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });
          addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    formKeyReleased(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel2.setText("Plat");

          jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel3.setText("Tanggal & Waktu");

          jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel4.setText("No Permintaan");

          JdTGL.setDate(new Date());
          JdTGL.setDateFormatString("dd-MM-yyyy");
          JdTGL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel12.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel12.setText("Keterangan");
          jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          jLabel13.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel13.setText("Jenis Pekerjaan");
          jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          jLabel14.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel14.setText("Ongkos Service");
          jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

          jLabel16.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel16.setText("KM Ganti Oli");

          jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jButton1.setText("SIMPAN");
          jButton1.addItemListener(new java.awt.event.ItemListener()
          {
               public void itemStateChanged(java.awt.event.ItemEvent evt)
               {
                    jButton1ItemStateChanged(evt);
               }
          });
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel17.setText("USER :");

          jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

          jLabel21.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel21.setText("Sopir");

          jLabel22.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel22.setText("Jenis Permintaan");

          jLabel23.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel23.setText("Jenis Perbaikan");

          jLabel24.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel24.setText("Prioritas Perbaikan");

          JcPlat.setQuery("SELECT `NoPolisi`FROM `ttruck`");
          JcPlat.excute();
          JcPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JcPlat.addItemListener(new java.awt.event.ItemListener()
          {
               public void itemStateChanged(java.awt.event.ItemEvent evt)
               {
                    JcPlatItemStateChanged(evt);
               }
          });
          JcPlat.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    JcPlatActionPerformed(evt);
               }
          });

          JCjenis.setQuery("SELECT `Jenis Service` FROM `tjenisservice` order by `No` asc");
          JCjenis.excute();
          JCjenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JCjenis.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JCjenisKeyReleased(evt);
               }
          });

          JTCari.setmaxtText(50);
          JTCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JTCari.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JTCariKeyReleased(evt);
               }
          });

          jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel5.setText("KM Mobil");

          JcKMO.setDisabledTextColor(new java.awt.Color(0, 51, 102));
          JcKMO.setEnabled(false);
          JcKMO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JcPemintaan.setQuery(QJcP1);
          JcPemintaan.setaawalkosong(false);
          JcPemintaan.excute();
          JcPemintaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JcPerbaikan.setQuery(QJcP2);
          JcPerbaikan.setaawalkosong(false);
          JcPerbaikan.excute();
          JcPerbaikan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JcPrioritas.setQuery(QJcP3);
          JcPrioritas.setaawalkosong(false);
          JcPrioritas.excute();
          JcPrioritas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          BtnUbah.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          BtnUbah.setText("Ubah");
          BtnUbah.setFocusable(false);
          BtnUbah.setName(""); // NOI18N

          org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BtnUbah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
          bindingGroup.addBinding(binding);

          BtnUbah.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    BtnUbahActionPerformed(evt);
               }
          });

          BtnRefresh.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          BtnRefresh.setText("Refresh");
          BtnRefresh.setFocusable(false);
          BtnRefresh.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    BtnRefreshActionPerformed(evt);
               }
          });

          JTBiaya.setmaxnum(1000000000);
          JTBiaya.setDisabledTextColor(new java.awt.Color(0, 51, 102));
          JTBiaya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JTBiaya.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JTBiayaKeyReleased(evt);
               }
          });

          JTKMMobil.setText("0");
          JTKMMobil.setDisabledTextColor(new java.awt.Color(0, 51, 102));
          JTKMMobil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JtNoPermintaan.setmaxtText(14);
          JtNoPermintaan.setText(F.GenNoPermintaan.GetNoPermintaanKerja(JcPerbaikan.getSelectedIndex()));
          JtNoPermintaan.setEnabled(false);
          JtNoPermintaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JtSopir.setmaxtText(50);
          JtSopir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jtCPlat.setmaxtText(50);
          jtCPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jtCPlat.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    jtCPlatKeyReleased(evt);
               }
          });

          jtUser.setText(F.Variablebanking.SUsername);
          jtUser.setEnabled(false);
          jtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JTKet.setmaxtText(100);
          JTKet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JTKet.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JTKetKeyReleased(evt);
               }
          });

          JTTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
          JTTime.setText(F.Datetostringwidthformat.getstringfromdate(new Date(),"HH:mm"));
          JTTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JTCatKhusus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel25.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel25.setText("Catatan Khusus :");

          JTable.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {

               },
               new String []
               {
                    "NO", "Jenis Permintaan", "Keterangan", "Ongkos Service"
               }
          )
          {
               boolean[] canEdit = new boolean []
               {
                    false, false, false, false
               };

               public boolean isCellEditable(int rowIndex, int columnIndex)
               {
                    return canEdit [columnIndex];
               }
          });
          JTable.getTableHeader().setReorderingAllowed(false);
          JTable.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });

               JTable.getTableHeader().setReorderingAllowed(false);
               DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
               rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
               for (int b = 2; b < JTable.getColumnCount(); b++)
               {
                    JTable.getColumnModel().getColumn(b).setCellRenderer(rightRenderer);
               }
               JTable.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         JTableKeyReleased(evt);
                    }
               });
               jScrollPane1.setViewportView(JTable);
               JTable.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "startEditing");
               JTable.setrender(3,"Number");

               BtnTambah.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
               BtnTambah.setText("Tambah");
               BtnTambah.setFocusable(false);

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement == null}"), BtnTambah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BtnTambah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BtnTambahActionPerformed(evt);
                    }
               });

               BtnHapus.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
               BtnHapus.setText("Hapus");
               BtnHapus.setFocusable(false);

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, JTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BtnHapus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BtnHapus.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BtnHapusActionPerformed(evt);
                    }
               });

               jButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
               jButton2.setText("SIMPAN DAN BARU");
               jButton2.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jButton2ActionPerformed(evt);
                    }
               });

               jButton3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
               jButton3.setText("SIMPAN DAN CETAK");
               jButton3.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jButton3ActionPerformed(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(10, 10, 10)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                   .addComponent(jLabel17)
                                   .addGap(4, 4, 4)
                                   .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jButton3)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(jButton2)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(jButton1))
                              .addGroup(layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addGroup(layout.createSequentialGroup()
                                                       .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                       .addComponent(JCjenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                  .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                                  .addComponent(JTKet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(JTBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(jScrollPane1))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                              .addGroup(layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JdTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JcPemintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JcPerbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JcPrioritas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JtSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(jtCPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(JtNoPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createSequentialGroup()
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel25)
                                             .addGap(4, 4, 4)
                                             .addComponent(JTCatKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(4, 4, 4)
                                             .addComponent(JcKMO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(jLabel5)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTKMMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGap(0, 81, Short.MAX_VALUE)))
                         .addContainerGap())
               );
               layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addComponent(jLabel18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                   .addGap(2, 2, 2)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(JtNoPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(220, 220, 220)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel12)
                                             .addComponent(jLabel14)))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(JTKet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(JTBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(JCjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(2, 2, 2)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(BtnTambah)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(BtnUbah)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(BtnHapus)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(BtnRefresh)
                                             .addGap(0, 56, Short.MAX_VALUE)))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel25))
                                        .addComponent(JTCatKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(11, 11, 11)
                                             .addComponent(jLabel17))
                                        .addGroup(layout.createSequentialGroup()
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                  .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(jButton1)
                                                  .addComponent(jButton2)
                                                  .addComponent(jButton3))))
                                   .addGap(11, 11, 11))
                              .addGroup(layout.createSequentialGroup()
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel3))
                                        .addComponent(JTTime)
                                        .addComponent(JdTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(8, 8, 8)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jtCPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(5, 5, 5)
                                             .addComponent(jLabel21))
                                        .addComponent(JtSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(6, 6, 6)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel22))
                                        .addComponent(JcPemintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(8, 8, 8)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel23))
                                        .addComponent(JcPerbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(6, 6, 6)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel24))
                                        .addComponent(JcPrioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGap(6, 6, 6)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addGap(2, 2, 2)
                                             .addComponent(jLabel16))
                                        .addComponent(JcKMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                             .addComponent(jLabel5)
                                             .addComponent(JTKMMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
               );

               jLabel2.getAccessibleContext().setAccessibleName("");
               jLabel3.getAccessibleContext().setAccessibleName("");
               jLabel4.getAccessibleContext().setAccessibleName("");
               JdTGL.getAccessibleContext().setAccessibleName("");
               jLabel16.getAccessibleContext().setAccessibleName("");
               jLabel21.getAccessibleContext().setAccessibleName("");
               jLabel22.getAccessibleContext().setAccessibleName("");
               jLabel23.getAccessibleContext().setAccessibleName("");
               jLabel24.getAccessibleContext().setAccessibleName("");
               JcPlat.getAccessibleContext().setAccessibleName("");
               jLabel5.getAccessibleContext().setAccessibleName("");
               JcPemintaan.getAccessibleContext().setAccessibleName("");
               JcPerbaikan.getAccessibleContext().setAccessibleName("");
               JcPrioritas.getAccessibleContext().setAccessibleName("");
               JTKMMobil.getAccessibleContext().setAccessibleName("");

               bindingGroup.bind();

               pack();
          }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JtNoPermintaan.setText(F.GenNoPermintaan.GetNoPermintaanKerja(JcPerbaikan.getSelectedIndex()));
        if (JcPlat.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(this, "Plat Harus Di Pilih Terlebih Dahulu");
        } else {
            int km = 0;
            if (JTable.getRowCount() != 0) {
                if (JTKMMobil.isEnabled()) {
                    km = JTKMMobil.getInt();
                } else if (JcKMO.isEnabled()) {
                    km = JTKMMobil.getInt();
                }
                List<String> list = new ArrayList<>();
                list.add("INSERT INTO `tbpermintaan`(`NoPermintaan`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`) VALUES ("
                        + "'" + JtNoPermintaan.getText() + "','" + F.Datetostringwidthformat.getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                        + "','" + JcPlat.getSelectedItem() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                        + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                        + ",'" + km + "','" + jtUser.getText() + "','" + JTCatKhusus.getText() + "')");
                Object[][] b = getTableData(JTable);
                for (int i = 0; i < b.length; i++) {
                    String bb = "";
                    for (int j = 0; j < b[i].length + 1; j++) {
                        if (j == b[i].length) {
                            bb += "'" + JtNoPermintaan.getText() + "'";
                        } else if ((j == b[i].length - 4) || (j == b[i].length - 1)) {
                            bb += "" + b[i][j] + ",";
                        } else {
                            bb += "'" + b[i][j] + "',";
                        }
                    }
                    list.add("INSERT INTO `tbdetailpermintaan`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`NoPermintaan`) VALUES (" + bb + ")");
                }
                RunMultiUpd runMultiUpd = new F.RunMultiUpd();
                runMultiUpd.setQuery(list);
                runMultiUpd.seterorm("Gagal Tambah Data !");
                int no = runMultiUpd.excute();
                if (no != 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil di simpan !!");
                    F.History.STambah("Tambah Data permintaan Service " + JtNoPermintaan.getText());
                    F.VarJFrame.tambahPermintaanKerja.dispose();
                    F.VarJFrame.tambahPermintaanKerja = null;
                    F.VarJFrame.menuPermintaanKerja.refresh();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Permintaan Service Tidak Boleh Kosong !");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCariKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            JCjenis.requestFocus();
            JCjenis.setSelectedIndex(0);
        } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
            if (JTable.getSelectedRow() != -1) {
                JTable.clearSelection();
                JCjenis.setSelectedIndex(0);
                JTKet.setText("");
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && JCjenis.getSelectedIndex() != -1) {
            JCjenis.hidePopup();
            JTKet.requestFocus();
        } else {
            JCjenis.setQuery("SELECT `Jenis Service`  FROM `tjenisservice` where `Jenis Service` like '%" + JTCari.getText() + "%'order by `No` asc");
            JCjenis.setaawalkosong(false);
            JCjenis.excute();
            JCjenis.showPopup();
        }
    }//GEN-LAST:event_JTCariKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        F.VarJFrame.tambahPermintaanKerja = null;
        if (F.VarJFrame.menuPermintaanKerja != null) {
            F.VarJFrame.menuPermintaanKerja.refresh();
        }
    }//GEN-LAST:event_formWindowClosing

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        if (JCjenis.getSelectedItem().equals("GANTI OLI MESIN") && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) < F.Variablebanking.MinGantiOli) && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) != -1)) {
            JOptionPane.showMessageDialog(this, "Tidak Bisa Ganti Oli karena Kilometer Ganti Oli Belum Cukup");
        } else if (JCjenis.getSelectedItem() == "") {
            JOptionPane.showMessageDialog(this, "Jenis Service Harus Di Pilih");
        } else if (JTable.getSelectedRow() != -1) {
            JTable.setValueAt(JCjenis.getSelectedItem(), JTable.getSelectedRow(), 1);
            JTable.setValueAt(JTKet.getText(), JTable.getSelectedRow(), 2);
            JTable.setValueAt(JTBiaya.getInt(), JTable.getSelectedRow(), 3);
            JOptionPane.showMessageDialog(this, "Berhasil Ubah Permintaan");
            RefreshsJtable();
            JTCari.requestFocus();
        }
    }//GEN-LAST:event_BtnUbahActionPerformed

    private void JcPlatItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_JcPlatItemStateChanged
    {//GEN-HEADEREND:event_JcPlatItemStateChanged
        setKMfromPlat(JcPlat.getSelectedItem());
        setenabdisabtextkm();
    }//GEN-LAST:event_JcPlatItemStateChanged

    private void jtCPlatKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jtCPlatKeyReleased
    {//GEN-HEADEREND:event_jtCPlatKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            JcPlat.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && JcPlat.getSelectedIndex() != -1) {
            JcPlat.hidePopup();
            JtSopir.requestFocus();
            setKMfromPlat(JcPlat.getSelectedItem());
            setenabdisabtextkm();
        } else {
            JcPlat.setQuery("SELECT `NoPolisi` FROM `ttruck` where `NoPolisi` like '%" + jtCPlat.getText() + "%' ");
            JcPlat.setaawalkosong(false);
            JcPlat.excute();
            JcPlat.showPopup();
        }
    }//GEN-LAST:event_jtCPlatKeyReleased

    private void JcPlatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JcPlatActionPerformed
    {//GEN-HEADEREND:event_JcPlatActionPerformed
        setenabdisabtextkm();
        setKMfromPlat(JcPlat.getSelectedItem());
        DefaultTableModel dm = (DefaultTableModel) JTable.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }//GEN-LAST:event_JcPlatActionPerformed

    void deleterowjtable(KeyEvent evt) {
        if (JTable.getSelectedRow() != -1) {
            if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
                if (JTable.getSelectedRow() != -1) {
                    ((DefaultTableModel) JTable.getModel()).removeRow(JTable.getSelectedRow());
                    for (int a = 0; a < JTable.getRowCount(); a++) {
                        JTable.setValueAt(a + 1, a, 0);
                    }
                    JOptionPane.showMessageDialog(this, "Berhasil Hapus Permintaan");
                    RefreshsJtable();
                    JTCari.requestFocus();
                }
            }
        }
    }
     private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnRefreshActionPerformed
     {//GEN-HEADEREND:event_BtnRefreshActionPerformed
         JTable.clearSelection();
         JCjenis.setSelectedIndex(0);
         JTKet.setText("");
     }//GEN-LAST:event_BtnRefreshActionPerformed

     private void JTBiayaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTBiayaKeyReleased
     {//GEN-HEADEREND:event_JTBiayaKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             if (BtnUbah.isEnabled() == false) {
                 if (JCjenis.getSelectedItem().equals("GANTI OLI MESIN") && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) < F.Variablebanking.MinGantiOli) && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) != -1)) {
                     JOptionPane.showMessageDialog(this, "Tidak Bisa Ganti Oli karena Kilometer Ganti Oli Belum Cukup");
                 } else if (JCjenis.getSelectedItem() == "") {
                     JOptionPane.showMessageDialog(this, "Jenis Service Harus Di Pilih");
                 } else {
                     DefaultTableModel model = (DefaultTableModel) JTable.getModel();
                     model.addRow(new Object[]{JTable.getRowCount() + 1, JCjenis.getSelectedItem(), JTKet.getText(), JTBiaya.getInt()});
                     JOptionPane.showMessageDialog(this, "Berhasil Tambah Permintaan");
                     RefreshsJtable();
                     JTCari.requestFocus();
                 }
             } else if (JCjenis.getSelectedItem().equals("GANTI OLI MESIN") && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) < F.Variablebanking.MinGantiOli) && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) != -1)) {
                 JOptionPane.showMessageDialog(this, "Tidak Bisa Ganti Oli karena Kilometer Ganti Oli Belum Cukup");
             } else if (JCjenis.getSelectedItem() == "") {
                 JOptionPane.showMessageDialog(this, "Jenis Service Harus Di Pilih");
             } else if (JTable.getSelectedRow() != -1) {
                 JTable.setValueAt(JCjenis.getSelectedItem(), JTable.getSelectedRow(), 1);
                 JTable.setValueAt(JTKet.getText(), JTable.getSelectedRow(), 2);
                 JTable.setValueAt(JTBiaya.getInt(), JTable.getSelectedRow(), 3);
                 JOptionPane.showMessageDialog(this, "Berhasil Ubah Permintaan");
                 RefreshsJtable();
                 JTCari.requestFocus();
             }
         }
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             if (JTable.getSelectedRow() != -1) {
                 JTable.clearSelection();
                 JCjenis.setSelectedIndex(0);
                 JTKet.setText("");
             }
         }
     }//GEN-LAST:event_JTBiayaKeyReleased

     private void JTableKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTableKeyReleased
     {//GEN-HEADEREND:event_JTableKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             if (JTable.getSelectedRow() != -1) {
                 JTCari.requestFocus();
             }

         } else if (evt.getKeyCode() == KeyEvent.VK_F5) {
             if (JTable.getSelectedRow() != -1) {
                 JTable.clearSelection();
                 JCjenis.setSelectedIndex(0);
                 JTKet.setText("");
             }
         }
         deleterowjtable(evt);
     }//GEN-LAST:event_JTableKeyReleased

     private void formKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_formKeyReleased
     {//GEN-HEADEREND:event_formKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             if (JTable.getSelectedRow() != -1) {
                 JTable.clearSelection();
                 JCjenis.setSelectedIndex(0);
                 JTKet.setText("");
             }
         }          // TODO add your handling code here:
     }//GEN-LAST:event_formKeyReleased

     private void JTKetKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTKetKeyReleased
     {//GEN-HEADEREND:event_JTKetKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             if (JTable.getSelectedRow() != -1) {
                 JTable.clearSelection();
                 JCjenis.setSelectedIndex(0);
                 JTKet.setText("");
             }
         } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             JTBiaya.requestFocus();
         }
         // TODO add your handling code here:
     }//GEN-LAST:event_JTKetKeyReleased

     private void JCjenisKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JCjenisKeyReleased
     {//GEN-HEADEREND:event_JCjenisKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             if (JTable.getSelectedRow() != -1) {
                 JTable.clearSelection();
                 JCjenis.setSelectedIndex(0);
                 JTKet.setText("");
             }
         } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             JTKet.requestFocus();
         }
         // TODO add your handling code here:
     }//GEN-LAST:event_JCjenisKeyReleased

     private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnTambahActionPerformed
     {//GEN-HEADEREND:event_BtnTambahActionPerformed

         if (JCjenis.getSelectedItem().equals("GANTI OLI MESIN") && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) < F.Variablebanking.MinGantiOli) && (Cek.JmlahKMO(JcPlat.getSelectedItem().toString()) != -1)) {
             JOptionPane.showMessageDialog(this, "Tidak Bisa Ganti Oli karena Kilometer Ganti Oli Belum Cukup");
         } else if (JCjenis.getSelectedItem() == "") {
             JOptionPane.showMessageDialog(this, "Jenis Service Harus Di Pilih");
         } else {
             DefaultTableModel model = (DefaultTableModel) JTable.getModel();
             model.addRow(new Object[]{JTable.getRowCount() + 1, JCjenis.getSelectedItem(), JTKet.getText(), JTBiaya.getInt()});
             JOptionPane.showMessageDialog(this, "Berhasil Tambah Permintaan");
             RefreshsJtable();
             JTCari.requestFocus();
         }
     }//GEN-LAST:event_BtnTambahActionPerformed

    void setSelectedData() {
        if (JTable.getSelectedRow() != -1) {
            int row = JTable.getSelectedRow();
            JCjenis.setSelectedItem(JTable.getValueAt(row, 1));
            JTKet.setText(JTable.getValueAt(row, 2).toString());
            JTBiaya.setInt(Integer.parseInt(JTable.getValueAt(row, 3).toString()));
        }
    }
     private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BtnHapusActionPerformed
     {//GEN-HEADEREND:event_BtnHapusActionPerformed
         if (JTable.getSelectedRow() != -1) {
             if (JTable.getSelectedRow() != -1) {
                 ((DefaultTableModel) JTable.getModel()).removeRow(JTable.getSelectedRow());
                 for (int a = 0; a < JTable.getRowCount(); a++) {
                     JTable.setValueAt(a + 1, a, 0);
                 }
                 JOptionPane.showMessageDialog(this, "Berhasil Hapus Permintaan");
                 RefreshsJtable();
                 JTCari.requestFocus();
             }
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BtnHapusActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
     {//GEN-HEADEREND:event_jButton2ActionPerformed

         JtNoPermintaan.setText(F.GenNoPermintaan.GetNoPermintaanKerja(JcPerbaikan.getSelectedIndex()));
         if (JcPlat.getSelectedItem() == "") {
             JOptionPane.showMessageDialog(this, "Plat Harus Di Pilih Terlebih Dahulu");
         } else if (JTable.getRowCount() != 0) {
             int km = 0;
             if (JTKMMobil.isEnabled()) {
                 km = JTKMMobil.getInt();
             } else if (JcKMO.isEnabled()) {
                 km = JTKMMobil.getInt();
             }
             List<String> list = new ArrayList<>();
             list.add("INSERT INTO `tbpermintaan`(`NoPermintaan`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`) VALUES ("
                     + "'" + JtNoPermintaan.getText() + "','" + F.Datetostringwidthformat.getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                     + "','" + JcPlat.getSelectedItem() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                     + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                     + ",'" + km + "','" + jtUser.getText() + "','" + JTCatKhusus.getText() + "')");
             Object[][] b = getTableData(JTable);
             for (int i = 0; i < b.length; i++) {
                 String bb = "";
                 for (int j = 0; j < b[i].length + 1; j++) {
                     if (j == b[i].length) {
                         bb += "'" + JtNoPermintaan.getText() + "'";
                     } else if ((j == b[i].length - 4) || (j == b[i].length - 1)) {
                         bb += "" + b[i][j] + ",";
                     } else {
                         bb += "'" + b[i][j] + "',";
                     }
                 }
                 list.add("INSERT INTO `tbdetailpermintaan`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`NoPermintaan`) VALUES (" + bb + ")");
             }
             RunMultiUpd runMultiUpd = new F.RunMultiUpd();
             runMultiUpd.setQuery(list);
             runMultiUpd.seterorm("Gagal Tambah Data !");
             int no = runMultiUpd.excute();
             if (no != 0) {
                 JOptionPane.showMessageDialog(this, "Data berhasil di simpan !!");
                 F.History.STambah("Tambah Data permintaan Service " + JtNoPermintaan.getText());
                 F.VarJFrame.tambahPermintaanKerja.dispose();
                 F.VarJFrame.tambahPermintaanKerja = null;
                 F.VarJFrame.menuPermintaanKerja.refresh();
                 if (tambahPermintaanKerja == null) {
                     tambahPermintaanKerja = new TambahPS();
                 }
             }
         } else {
             JOptionPane.showMessageDialog(this, "Permintaan Service Tidak Boleh Kosong !");
         }
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
     {//GEN-HEADEREND:event_jButton3ActionPerformed
         JtNoPermintaan.setText(F.GenNoPermintaan.GetNoPermintaanKerja(JcPerbaikan.getSelectedIndex()));
         if (JcPlat.getSelectedItem() == "") {
             JOptionPane.showMessageDialog(this, "Plat Harus Di Pilih Terlebih Dahulu");
         } else if (JTable.getRowCount() != 0) {

             int km = 0;
             if (JTKMMobil.isEnabled()) {
                 km = JTKMMobil.getInt();
             } else if (JcKMO.isEnabled()) {
                 km = JTKMMobil.getInt();
             }
             List<String> list = new ArrayList<>();
             list.add("INSERT INTO `tbpermintaan`(`NoPermintaan`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`) VALUES ("
                     + "'" + JtNoPermintaan.getText() + "','" + F.Datetostringwidthformat.getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                     + "','" + JcPlat.getSelectedItem() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                     + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                     + ",'" + km + "','" + jtUser.getText() + "','" + JTCatKhusus.getText() + "')");
             Object[][] b = getTableData(JTable);
             for (int i = 0; i < b.length; i++) {
                 String bb = "";
                 for (int j = 0; j < b[i].length + 1; j++) {
                     if (j == b[i].length) {
                         bb += "'" + JtNoPermintaan.getText() + "'";
                     } else if ((j == b[i].length - 4) || (j == b[i].length - 1)) {
                         bb += "" + b[i][j] + ",";
                     } else {
                         bb += "'" + b[i][j] + "',";
                     }
                 }
                 list.add("INSERT INTO `tbdetailpermintaan`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`NoPermintaan`) VALUES (" + bb + ")");
             }
             RunMultiUpd runMultiUpd = new F.RunMultiUpd();
             runMultiUpd.setQuery(list);
             runMultiUpd.seterorm("Gagal Tambah Data !");
             int no = runMultiUpd.excute();
             if (no != 0) {
                 JOptionPane.showMessageDialog(this, "Data berhasil di simpan !!");
                 F.History.STambah("Tambah Data permintaan Service " + JtNoPermintaan.getText());
                 F.VarJFrame.tambahPermintaanKerja.dispose();
                 F.VarJFrame.tambahPermintaanKerja = null;
                 if (tambahPermintaanKerja == null) {
                     tambahPermintaanKerja = new TambahPS();
                 }
                 HashMap hashs = new HashMap();
                 String Statusjcom;
                 String StatusOrder;
                 String Cari;
                 hashs.put("Title", "SURAT PERMINTAAN SERVICE");
                 hashs.put("NoPermintaanKerja", JtNoPermintaan.getText());
                 hashs.put("KaMekanik", Mechanik);
                 hashs.put("Pimpinan", Pimpinan);
                 hashs.put("PrintedBy", "Di Print Oleh " + SUsername + " Pada " + getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
                 FLaporan fLaporan = new F.FLaporan();
                 fLaporan.sethashmap(hashs);
                 fLaporan.setfilename("PermintaanKerja");
                 fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
                 fLaporan.excute();
                 RunUpd runUpd = new RunUpd();
                 runUpd.setQuery("UPDATE `tbpermintaan` SET `Print`='Yes' WHERE `NoPermintaan`='" + JtNoPermintaan.getText() + "'");
                 runUpd.excute();
                 F.VarJFrame.menuPermintaanKerja.refresh();
             }
         } else {
             JOptionPane.showMessageDialog(this, "Permintaan Service Tidak Boleh Kosong !");
         }
     }//GEN-LAST:event_jButton3ActionPerformed

     private void jButton1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_jButton1ItemStateChanged
     {//GEN-HEADEREND:event_jButton1ItemStateChanged
         // TODO add your handling code here:
     }//GEN-LAST:event_jButton1ItemStateChanged

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BtnHapus;
     private javax.swing.JButton BtnRefresh;
     private javax.swing.JButton BtnTambah;
     private javax.swing.JButton BtnUbah;
     private F.JcomFromDb JCjenis;
     private F.RibuanTextField JTBiaya;
     private F.JackTextField JTCari;
     private F.JackTextField JTCatKhusus;
     private F.RibuanTextField JTKMMobil;
     private F.JackTextField JTKet;
     private javax.swing.JFormattedTextField JTTime;
     private F.Jktable JTable;
     private F.JNumberTextField JcKMO;
     private F.JcomFromDb JcPemintaan;
     private F.JcomFromDb JcPerbaikan;
     private F.JcomFromDb JcPlat;
     private F.JcomFromDb JcPrioritas;
     private com.toedter.calendar.JDateChooser JdTGL;
     private F.JackTextField JtNoPermintaan;
     private F.JackTextField JtSopir;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel22;
     private javax.swing.JLabel jLabel23;
     private javax.swing.JLabel jLabel24;
     private javax.swing.JLabel jLabel25;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JScrollPane jScrollPane1;
     private F.JackTextField jtCPlat;
     private F.JackTextField jtUser;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(TambahPS.class.getName());

}
