/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import F.RunUpd;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JACK
 */
public class Mekanik extends javax.swing.JFrame {

    /**
     * Creates new form JenisService
     */
    public Mekanik() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle(NamaMaster);
        setVisible(true);
        BTambah.setVisible(F.Variablebanking.hak[13]);
        BUbah.setVisible(F.Variablebanking.hak[14]);
        BHapus.setVisible(F.Variablebanking.hak[15]);
    }
    String NamaMaster = "Mekanik";
    String SelecQ = "SELECT `No` as 'No', `Nama` as 'Nama', if(`Status`=0,'Aktiv','Tidak Aktiv') as 'Status' FROM `tbmekanik`";
    String SelecQ2 = "SELECT `No`, `Nama`, if(`Status`=0,'Aktiv','Tidak Aktiv') FROM `tbmekanik`";
    String QInsert;
    String QUpdate;
    String QDelete;

    void GetQinsert() {
        QInsert = "INSERT INTO `tbmekanik`(`Nama`, `Status`) VALUES ('" + JTPlat.getText() + "'," + (JCStatus.getSelectedIndex()) + ")";
    }

    void GetQupdate() {
        QUpdate = "UPDATE `tbmekanik` SET `Nama`='" + JTPlat.getText() + "',`Status`= " + (JCStatus.getSelectedIndex()) + " WHERE `No`= " + jktable1.getint(jktable1.getSelectedRow(), 0) + "";
    }

    void getQDelete() {
        QDelete = "DELETE FROM `tbmekanik` WHERE `No`=" + jktable1.getint(jktable1.getSelectedRow(), 0) + "";
    }

    void FCari() {
        Vector v = jcomFromDBtable1.getcoloumname();
        jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%'" + " Order By No Desc");
        jktable1.tampilkan();
    }

    void getSelectedData() {
        if (jktable1.getSelectedRow() != -1) {
            int bar = jktable1.getSelectedRow();
            JTNO.setText(jktable1.getstring(bar, 0));
            JTPlat.setText(jktable1.getstring(bar, 1));
            JCStatus.setSelectedItem(jktable1.getValueAt(bar, 2));
        }
    }

    void refresh() {
        JTNO.setText("");
        JTPlat.setText("");
        JCStatus.setSelectedIndex(0);
        JTCari.setText("");
        jktable1.setQuery(SelecQ + " Order By No Desc");
        jktable1.tampilkan();
        jktable1.clearSelection();
    }

    boolean isvalidinput() {
        if (JTPlat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "KA Mekanik Tidak Boleh Kosong");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jNumberTextField1 = new F.JNumberTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          jktable1 = new F.Jktable();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          JTNO = new F.JackTextField();
          BTambah = new javax.swing.JButton();
          BUbah = new javax.swing.JButton();
          BHapus = new javax.swing.JButton();
          BRefresh = new javax.swing.JButton();
          jcomFromDBtable1 = new F.JcomFromDBtable();
          jLabel9 = new javax.swing.JLabel();
          JTPlat = new F.JackTextField();
          JCStatus = new F.JcomFromDb();
          JTCari = new F.JackTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jktable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String []
               {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jktable1.setQuery(SelecQ+" Order By No Desc");
          jktable1.tampilkan();
          jScrollPane1.setViewportView(jktable1);
          jktable1.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });

               jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel1.setText("Cari Berdasarkan :");

               jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel2.setText("No");

               jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel3.setText("Mekanik");

               JTNO.setmaxtText(3);
               JTNO.setEnabled(false);
               JTNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               BTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BTambah.setText("Tambah");

               org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement == null}"), BTambah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BTambah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BTambahActionPerformed(evt);
                    }
               });

               BUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BUbah.setText("Ubah");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BUbah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BUbah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BUbahActionPerformed(evt);
                    }
               });

               BHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BHapus.setText("Hapus");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BHapus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BHapus.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BHapusActionPerformed(evt);
                    }
               });

               BRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BRefresh.setText("Refresh");
               BRefresh.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BRefreshActionPerformed(evt);
                    }
               });

               jcomFromDBtable1.setQuery1(SelecQ);
               jcomFromDBtable1.setQuery2(SelecQ2);
               jcomFromDBtable1.excute1();
               jcomFromDBtable1.excute2();
               jcomFromDBtable1.setSelectedIndex(1);
               jcomFromDBtable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jcomFromDBtable1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jcomFromDBtable1ActionPerformed(evt);
                    }
               });

               jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel9.setText("Status");

               JTPlat.setmaxtText(20);
               JTPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               JCStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aktiv", "Tidak Aktiv" }));
               JCStatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               JTCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               JTCari.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         JTCariKeyReleased(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                   .addGap(10, 10, 10)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTNO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel3)
                                                  .addComponent(jLabel9))
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(JCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(JTPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel1)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGap(0, 0, Short.MAX_VALUE))
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                   .addGap(0, 0, Short.MAX_VALUE)
                                   .addComponent(BRefresh)
                                   .addGap(6, 6, 6)
                                   .addComponent(BHapus)
                                   .addGap(6, 6, 6)
                                   .addComponent(BUbah)
                                   .addGap(6, 6, 6)
                                   .addComponent(BTambah)))
                         .addContainerGap())
               );

               layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel9});

               layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                         .addGap(12, 12, 12)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel1)
                              .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(6, 6, 6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(JTNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(6, 6, 6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(JTPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(6, 6, 6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel9)
                              .addComponent(JCStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(6, 6, 6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(BRefresh)
                              .addComponent(BHapus)
                              .addComponent(BUbah)
                              .addComponent(BTambah))
                         .addContainerGap())
               );

               layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BHapus, BRefresh, BTambah, BUbah, JCStatus, JTCari, JTNO, JTPlat, jLabel1, jLabel2, jLabel3, jLabel9, jcomFromDBtable1});

               bindingGroup.bind();

               pack();
          }// </editor-fold>//GEN-END:initComponents

    private void BRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_BRefreshActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        if (isvalidinput()) {
            GetQinsert();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QInsert);//
            runUpd.seterorm("Gagal Tambah Data " + NamaMaster);//
            int no = runUpd.excute();
            if (no != 0) {
                JOptionPane.showMessageDialog(this, "Berhasil Tambah Data " + NamaMaster);//
                refresh();
                F.History.STambah("Tambah Data " + NamaMaster + " " + JTPlat.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Pilihan Tidak Boleh Kosong !");
            }
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        if (isvalidinput()) {
            GetQupdate();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QUpdate);//
            runUpd.seterorm("Gagal Ubah Data " + NamaMaster);
            int no = runUpd.excute();
            if (no != 0) {
                JOptionPane.showMessageDialog(this, "Berhasil Ubah Data " + NamaMaster);
                refresh();
                F.History.STambah("Ubah Data " + NamaMaster + " " + JTNO.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Pilihan Harus Di Isi");
            }
        }
    }//GEN-LAST:event_BUbahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        if (F.JackOptionpane.jackop("Apakah Anda Yakin Mau Menghapus Data " + NamaMaster)) {
            getQDelete();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QDelete);
            runUpd.seterorm("Gagal Hapus Data " + NamaMaster);
            int no = runUpd.excute();
            if (no != 0) {
                JOptionPane.showMessageDialog(this, "Berhasil Hapus Data " + NamaMaster);
                refresh();
                F.History.STambah("Hapus Data " + NamaMaster + " " + JTNO.getText());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Batal Menghapus Data " + NamaMaster);
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void jcomFromDBtable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomFromDBtable1ActionPerformed
        FCari();        // TODO add your handling code here:
    }//GEN-LAST:event_jcomFromDBtable1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        F.VarJFrame.truck = null;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

     private void JTCariKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTCariKeyReleased
     {//GEN-HEADEREND:event_JTCariKeyReleased
         Vector v = jcomFromDBtable1.getcoloumname();
         jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%'");
         jktable1.tampilkan();
     }//GEN-LAST:event_JTCariKeyReleased

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BHapus;
     private javax.swing.JButton BRefresh;
     private javax.swing.JButton BTambah;
     private javax.swing.JButton BUbah;
     private F.JcomFromDb JCStatus;
     private F.JackTextField JTCari;
     private F.JackTextField JTNO;
     private F.JackTextField JTPlat;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel9;
     private F.JNumberTextField jNumberTextField1;
     private javax.swing.JScrollPane jScrollPane1;
     private F.JcomFromDBtable jcomFromDBtable1;
     private F.Jktable jktable1;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables

}
