/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Master;

import static F.JackOptionpane.jackop;
import F.RunUpd;
import static F.VarJFrame.pks;
import static F.Variablebanking.hak;
import java.util.Vector;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JACK
 */
public class PKS extends javax.swing.JFrame {

    /**
     * Creates new form JenisService
     */
    public PKS() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle(NamaMaster);
        setVisible(true);
        BTambah.setVisible(hak[10]);
        BUbah.setVisible(hak[11]);
        BHapus.setVisible(hak[12]);
    }
    String NamaMaster = "PKS";
    String SelecQ = "SELECT `NoPks` as 'NO', `AliasPKS` as 'PKS', `NamaPKS` as 'Nama', `AlamatPKS`as 'Alamat' FROM `tpks` ";
    String SelecQ2 = "SELECT `NoPks`, `AliasPKS`, `NamaPKS`, `AlamatPKS` FROM `tpks`";
    String QInsert;
    String QUpdate;
    String QDelete;

    void GetQinsert() {
        QInsert = "INSERT INTO `tpks`(`AliasPKS`, `NamaPKS`, `AlamatPKS`) VALUES ('" + JTPKS.getText() + "','" + JTNama.getText() + "','" + JTAlamat.getText() + "')";
    }

    void GetQupdate() {
        QUpdate = "UPDATE `tpks` SET `AliasPKS`= '" + JTPKS.getText() + "',`NamaPKS`= '" + JTNama.getText() + "',`AlamatPKS`= '" + JTAlamat.getText() + "' WHERE `NoPks`='" + JTNO.getText() + "'";
    }

    void getQDelete() {
        QDelete = "DELETE FROM `tpks` WHERE `NoPks`='" + JTNO.getText() + "'";
    }

    void FCari() {
        Vector v = jcomFromDBtable1.getcoloumname();
        jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%' " + " Order By No Desc");
        jktable1.tampilkan();
    }

    void getSelectedData() {
        int bar = jktable1.getSelectedRow();
        JTNO.setText(jktable1.getstring(bar, 0));
        JTPKS.setText(jktable1.getstring(bar, 1));
        JTNama.setText(jktable1.getstring(bar, 2));
        JTAlamat.setText(jktable1.getstring(bar, 3));
    }

    void refresh() {
        jktable1.setQuery(SelecQ + " Order By No Desc");
        JTAlamat.setText("");//
        JTCari.setText("");//
        JTNO.setText("");//
        JTNama.setText("");//
        JTPKS.setText("");//
        jktable1.tampilkan();
        jktable1.clearSelection();
    }

    boolean isvalidinput() {
        if (JTPKS.getText().isEmpty()) {
            showMessageDialog(this, "PKS Tidak Boleh Kosong");
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jNumberTextField1 = new F.JNumberTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          jktable1 = new F.Jktable();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          JTNO = new F.JackTextField();
          JTPKS = new F.JackTextField();
          BTambah = new javax.swing.JButton();
          BUbah = new javax.swing.JButton();
          BHapus = new javax.swing.JButton();
          BRefresh = new javax.swing.JButton();
          JTAlamat = new F.JackTextField();
          jLabel6 = new javax.swing.JLabel();
          JTNama = new F.JackTextField();
          jcomFromDBtable1 = new F.JcomFromDBtable();
          JTCari = new F.JackTextField();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jktable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String []
               {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jktable1.setName(""); // NOI18N
          jktable1.setRequestFocusEnabled(false);
          jktable1.setVerifyInputWhenFocusTarget(false);
          jktable1.setQuery(SelecQ+" Order By No Desc");
          jktable1.tampilkan();
          jScrollPane1.setViewportView(jktable1);
          jktable1.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });

               jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel1.setText("Cari Berdasarkan");

               jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel2.setText("No");

               jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel3.setText("PKS");

               jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel5.setText("Nama PKS");

               JTNO.setmaxtText(3);
               JTNO.setEnabled(false);
               JTNO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               JTPKS.setmaxtText(20);
               JTPKS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               BTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BTambah.setText("Tambah");

               org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement == null}"), BTambah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BTambah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BTambahActionPerformed(evt);
                    }
               });

               BUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BUbah.setText("Ubah");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BUbah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BUbah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BUbahActionPerformed(evt);
                    }
               });

               BHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BHapus.setText("Hapus");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BHapus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BHapus.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BHapusActionPerformed(evt);
                    }
               });

               BRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BRefresh.setText("Refresh");
               BRefresh.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BRefreshActionPerformed(evt);
                    }
               });

               JTAlamat.setmaxtText(45);
               JTAlamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel6.setText("Alamat");

               JTNama.setmaxtText(45);
               JTNama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               jcomFromDBtable1.setQuery1(SelecQ);
               jcomFromDBtable1.setQuery2(SelecQ2);
               jcomFromDBtable1.excute1();
               jcomFromDBtable1.excute2();
               jcomFromDBtable1.setSelectedIndex(1);
               jcomFromDBtable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jcomFromDBtable1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jcomFromDBtable1ActionPerformed(evt);
                    }
               });

               JTCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               JTCari.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         JTCariKeyReleased(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                   .addGap(10, 10, 10)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel1)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel2)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTNO, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel3)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTPKS, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTNama, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                             .addComponent(jLabel6)
                                             .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                             .addComponent(JTAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGap(0, 0, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                   .addGap(0, 0, Short.MAX_VALUE)
                                   .addComponent(BRefresh)
                                   .addGap(6, 6, 6)
                                   .addComponent(BHapus)
                                   .addGap(6, 6, 6)
                                   .addComponent(BUbah)
                                   .addGap(6, 6, 6)
                                   .addComponent(BTambah)))
                         .addContainerGap())
               );

               layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel5, jLabel6});

               layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                         .addGap(17, 17, 17)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel1)
                              .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(9, 9, 9)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel2)
                              .addComponent(JTNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(6, 6, 6)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel3)
                              .addComponent(JTPKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel5)
                              .addComponent(JTNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(9, 9, 9)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel6)
                              .addComponent(JTAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGap(14, 14, 14)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(BRefresh)
                              .addComponent(BHapus)
                              .addComponent(BUbah)
                              .addComponent(BTambah))
                         .addContainerGap())
               );

               layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BHapus, BRefresh, BTambah, BUbah, JTAlamat, JTCari, JTNO, JTNama, JTPKS, jLabel1, jLabel2, jLabel3, jLabel5, jLabel6, jcomFromDBtable1});

               bindingGroup.bind();

               pack();
          }// </editor-fold>//GEN-END:initComponents

    private void BRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_BRefreshActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        if (isvalidinput()) {
            GetQinsert();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QInsert);//
            runUpd.seterorm("Gagal Tambah Data " + NamaMaster);//
            int no = runUpd.excute();
            if (no != 0) {
                showMessageDialog(this, "Berhasil Tambah Data " + NamaMaster);//
                refresh();
                F.History.STambah("Tambah Data " + NamaMaster + " " + JTPKS.getText());
            }
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        if (isvalidinput()) {
            GetQupdate();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QUpdate);//
            runUpd.seterorm("Gagal Ubah Data " + NamaMaster);
            int no = runUpd.excute();
            if (no != 0) {
                showMessageDialog(this, "Berhasil Ubah Data " + NamaMaster);
                refresh();
                F.History.STambah("Ubah Data " + NamaMaster + " " + JTNO.getText());
            }
        }
    }//GEN-LAST:event_BUbahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        if (jackop("Apakah Anda Yakin Mau Menghapus Data " + NamaMaster)) {
            getQDelete();
            RunUpd runUpd = new F.RunUpd();
            runUpd.setQuery(QDelete);
            runUpd.seterorm("Gagal Hapus Data " + NamaMaster);
            int no = runUpd.excute();
            if (no != 0) {
                showMessageDialog(this, "Berhasil Hapus Data " + NamaMaster);
                refresh();
                F.History.STambah("Hapus Data " + NamaMaster + " " + JTNO.getText());
            }
        } else {
            showMessageDialog(this, "Batal Menghapus Data " + NamaMaster);
        }
    }//GEN-LAST:event_BHapusActionPerformed

    private void jcomFromDBtable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomFromDBtable1ActionPerformed
        FCari();        // TODO add your handling code here:
    }//GEN-LAST:event_jcomFromDBtable1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        pks = null;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

     private void JTCariKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JTCariKeyReleased
     {//GEN-HEADEREND:event_JTCariKeyReleased
         Vector v = jcomFromDBtable1.getcoloumname();
         jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%'");
         jktable1.tampilkan();
     }//GEN-LAST:event_JTCariKeyReleased

    /**
     * @param args the command line arguments
     */
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BHapus;
     private javax.swing.JButton BRefresh;
     private javax.swing.JButton BTambah;
     private javax.swing.JButton BUbah;
     private F.JackTextField JTAlamat;
     private F.JackTextField JTCari;
     private F.JackTextField JTNO;
     private F.JackTextField JTNama;
     private F.JackTextField JTPKS;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private F.JNumberTextField jNumberTextField1;
     private javax.swing.JScrollPane jScrollPane1;
     private F.JcomFromDBtable jcomFromDBtable1;
     private F.Jktable jktable1;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables

}
