/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses.SPK;

import F.FLaporan;
import F.RunMultiUpd;
import F.RunSelctOne;
import F.RunUpd;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author JACK
 */
public class MSPK extends javax.swing.JFrame {

    /**
     * Creates new form JenisService
     */
    public MSPK() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle(NamaMaster);
        setVisible(true);
        BTambah.setVisible(F.Variablebanking.hak[22]);
        BUbah.setVisible(F.Variablebanking.hak[23]);
        BHapus.setVisible(F.Variablebanking.hak[24]);
    }

    String NamaMaster = "Perintah Kerja";
    String SelecQ = "SELECT  a.`No` as 'NO', a.`NoPerintahKerja` as 'No SPK', a.`NoPermintaan` as 'NoPermintaan' ,DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i') as 'Tgl Permintaan',DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i') as 'Tanggal SPK', a.`Plat` as 'Plat', a.`Sopir` as 'Sopir', IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as 'Jenis Permintaan', if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror'))) as 'Jenis Pekerjaan', if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda', if(a.`TingkatPekerjaan`=1,'Darurat','Eror')) as 'Tingkat Pekerjaan', a.`KMT` as 'KM Truck', a.`User` as 'User',a.`CatKhusus` as 'Catatan Khusus', a.`Print` as 'Print' FROM `tbperintahkerja` a join `tbpermintaan` b on a.`NoPermintaan` =b.`NoPermintaan` ";
    String SelecQ2 = "SELECT  a.`No` as 'a.`No`',a.`NoPerintahKerja` as 'a.`NoPerintahKerja`', a.`NoPermintaan` as 'a.`NoPermintaan`', DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i') as \"DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i')\", DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i') as \"DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i')\", a.`Plat` as 'a.`Plat`', a.`Sopir` as 'a.`Sopir`', IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as \"IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror')))\", if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror'))) as \"if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror')))\", if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda', if(a.`TingkatPekerjaan`=1,'Darurat','Eror')) as \"if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda', if(a.`TingkatPekerjaan`=1,'Darurat','Eror'))\",a.`KMT` as 'a.`KMT`',a.`User` as 'a.`User`',a.`CatKhusus` as 'a.CatKhusus' , a.`Print` as 'print' FROM `tbperintahkerja` a join `tbpermintaan` b on a.`NoPermintaan` =b.`NoPermintaan`";
    String QInsert;
    String QUpdate;
    String QDelete1;
    String QDelete2;
    String QDelete3;
    String QDelete4;

    void getQDelete() {
        RunSelctOne runSelctOne = new F.RunSelctOne();
        runSelctOne.setQuery("SELECT `NoPermintaan` FROM `tbperintahkerja` WHERE `NoPerintahKerja` = '" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'");
        runSelctOne.seterorm("gagal Ganti Pass");
        String NoPermintaan = runSelctOne.excute();
        System.out.println("PERMINTAAN " + NoPermintaan);
        QDelete1 = "DELETE FROM `tbdetailperintahkerja` WHERE `NoPerintahKerja` = '" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'";
        QDelete2 = "DELETE FROM `tbperintahkerja` WHERE `NoPerintahKerja` = '" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "'";
        QDelete3 = "DELETE FROM `tbdetailpermintaan` WHERE `NoPermintaan` = '" + NoPermintaan + "'";
        QDelete4 = "DELETE FROM `tbpermintaan` WHERE `NoPermintaan` = '" + NoPermintaan + "'";
    }

    void getSelectedData() {
        int bar = jktable1.getSelectedRow();
    }

    /**
     *
     */
    public void refresh() {
        jktable1.setQuery(SelecQ + " Order By a.No Desc limit 100");
        jktable1.tampilkan();
        jktable1.clearSelection();
        JTCari.setText("");
        jcomFromDBtable1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {
          bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

          jScrollPane1 = new javax.swing.JScrollPane();
          jktable1 = new F.Jktable();
          jLabel1 = new javax.swing.JLabel();
          JTCari = new javax.swing.JTextField();
          BTambah = new javax.swing.JButton();
          BUbah = new javax.swing.JButton();
          BHapus = new javax.swing.JButton();
          BRefresh = new javax.swing.JButton();
          jcomFromDBtable1 = new F.JcomFromDBtable();
          jButton1 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jktable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String []
               {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          jktable1.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    jktable1KeyReleased(evt);
               }
          });
          jktable1.setQuery(SelecQ+"order by a.`No` desc");
          jktable1.tampilkan();
          jScrollPane1.setViewportView(jktable1);
          jktable1.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });

               jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jLabel1.setText("Cari Berdasarkan :");

               JTCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               JTCari.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         JTCariKeyReleased(evt);
                    }
               });

               BTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BTambah.setText("Tambah");

               org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement == null}"), BTambah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BTambah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BTambahActionPerformed(evt);
                    }
               });
               BTambah.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BTambahKeyReleased(evt);
                    }
               });

               BUbah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BUbah.setText("Ubah");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BUbah, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BUbah.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BUbahActionPerformed(evt);
                    }
               });
               BUbah.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BUbahKeyReleased(evt);
                    }
               });

               BHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BHapus.setText("Hapus");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), BHapus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               BHapus.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BHapusActionPerformed(evt);
                    }
               });
               BHapus.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BHapusKeyReleased(evt);
                    }
               });

               BRefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               BRefresh.setText("Refresh");
               BRefresh.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         BRefreshActionPerformed(evt);
                    }
               });
               BRefresh.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         BRefreshKeyReleased(evt);
                    }
               });

               jcomFromDBtable1.setQuery1(SelecQ);
               jcomFromDBtable1.setQuery2(SelecQ2);
               jcomFromDBtable1.excute1();
               jcomFromDBtable1.excute2();
               jcomFromDBtable1.setSelectedIndex(1);
               jcomFromDBtable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jcomFromDBtable1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jcomFromDBtable1ActionPerformed(evt);
                    }
               });
               jcomFromDBtable1.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         jcomFromDBtable1KeyReleased(evt);
                    }
               });

               jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
               jButton1.setText("Print");

               binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jktable1, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
               bindingGroup.addBinding(binding);

               jButton1.addActionListener(new java.awt.event.ActionListener()
               {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                         jButton1ActionPerformed(evt);
                    }
               });
               jButton1.addKeyListener(new java.awt.event.KeyAdapter()
               {
                    public void keyReleased(java.awt.event.KeyEvent evt)
                    {
                         jButton1KeyReleased(evt);
                    }
               });

               javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
               getContentPane().setLayout(layout);
               layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addGap(10, 10, 10)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(jScrollPane1)
                              .addGroup(layout.createSequentialGroup()
                                   .addComponent(jLabel1)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                                   .addComponent(jButton1)
                                   .addGap(6, 6, 6)
                                   .addComponent(BRefresh)
                                   .addGap(6, 6, 6)
                                   .addComponent(BHapus)
                                   .addGap(6, 6, 6)
                                   .addComponent(BUbah)
                                   .addGap(6, 6, 6)
                                   .addComponent(BTambah)))
                         .addContainerGap())
               );
               layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel1)
                                   .addComponent(jcomFromDBtable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(JTCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jButton1)
                                   .addComponent(BRefresh)
                                   .addComponent(BHapus)
                                   .addComponent(BUbah)
                                   .addComponent(BTambah)))
                         .addGap(12, 12, 12))
               );

               bindingGroup.bind();

               pack();
          }// </editor-fold>//GEN-END:initComponents

    private void BRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_BRefreshActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
        if (F.VarJFrame.tambahPerintahKerja == null) {
            F.VarJFrame.tambahPerintahKerja = new TambahSPK();
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void BUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUbahActionPerformed
        if (Proses.PS.Cek.isadaopname(jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString()) != null) {
            JOptionPane.showMessageDialog(this, "Opname Telah dibuat Tidak Dapat Di Rubah");
        } else if (F.VarJFrame.ubahPerintahKerja == null) {
            F.VarJFrame.ubahPerintahKerja = new UbahSPK(jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_BUbahActionPerformed

    private void BHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHapusActionPerformed
        if (F.JackOptionpane.jackop("Apakah Anda Yakin Mau Menghapus Data " + NamaMaster)) {
            String H = jktable1.getValueAt(jktable1.getSelectedRow(), 1).toString();
            getQDelete();
            RunMultiUpd runMultiUpd = new F.RunMultiUpd();
            Vector v = new Vector();
            //System.out.println("Q1 "+QDelete1);
            v.add(QDelete1);
            //System.out.println("Q1 "+QDelete2);
            v.add(QDelete2);
            //System.out.println("Q1 "+QDelete3);
            v.add(QDelete3);
            //System.out.println("Q1 "+QDelete4);
            v.add(QDelete4);
            runMultiUpd.setQuery(v);
            runMultiUpd.seterorm("Gagal Hapus Data " + NamaMaster);
            int no = runMultiUpd.excute();
            if (no != 0) {
                JOptionPane.showMessageDialog(this, "Berhasil Hapus Data " + NamaMaster);
                refresh();
                F.History.STambah("Hapus Data SPK " + NamaMaster + " " + H);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Batal Menghapus Data " + NamaMaster);
        }
    }//GEN-LAST:event_BHapusActionPerformed

    void FCari() {
        Vector v = jcomFromDBtable1.getcoloumname();
        jktable1.setQuery(SelecQ + " where " + v.get(jcomFromDBtable1.getSelectedIndex()) + " like '%" + JTCari.getText() + "%' order by a.No Desc limit 100");
        jktable1.tampilkan();
    }
    private void JTCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTCariKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_F5) {
            refresh();
        }
        FCari();
    }//GEN-LAST:event_JTCariKeyReleased
    private void jcomFromDBtable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomFromDBtable1ActionPerformed
        FCari();        // TODO add your handling code here:
    }//GEN-LAST:event_jcomFromDBtable1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        F.VarJFrame.menuPerintahKerja = null;        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         hashs.put("Title", "SURAT PERINTAH KERJA");
         hashs.put("NoPerintahKerja", jktable1.getValueAt(jktable1.getSelectedRow(), 1));
         hashs.put("KaMekanik", F.Variablebanking.Mechanik);
         hashs.put("Pimpinan", F.Variablebanking.Pimpinan);
         hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("PerintahKerja");
         fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
         fLaporan.excute();
         RunUpd runUpd = new RunUpd();
         runUpd.setQuery("UPDATE `tbperintahkerja` SET `Print`='Yes' WHERE `NoPerintahKerja`='" + jktable1.getValueAt(jktable1.getSelectedRow(), 1) + "' limit 100");
         runUpd.excute();
         F.VarJFrame.menuPerintahKerja.refresh();
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jktable1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jktable1KeyReleased
     {//GEN-HEADEREND:event_jktable1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jktable1KeyReleased

     private void jcomFromDBtable1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jcomFromDBtable1KeyReleased
     {//GEN-HEADEREND:event_jcomFromDBtable1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jcomFromDBtable1KeyReleased

     private void jButton1KeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jButton1KeyReleased
     {//GEN-HEADEREND:event_jButton1KeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jButton1KeyReleased

     private void BRefreshKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BRefreshKeyReleased
     {//GEN-HEADEREND:event_BRefreshKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BRefreshKeyReleased

     private void BHapusKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BHapusKeyReleased
     {//GEN-HEADEREND:event_BHapusKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BHapusKeyReleased

     private void BUbahKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BUbahKeyReleased
     {//GEN-HEADEREND:event_BUbahKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BUbahKeyReleased

     private void BTambahKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_BTambahKeyReleased
     {//GEN-HEADEREND:event_BTambahKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_F5) {
             refresh();
         }          // TODO add your handling code here:
     }//GEN-LAST:event_BTambahKeyReleased

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton BHapus;
     private javax.swing.JButton BRefresh;
     private javax.swing.JButton BTambah;
     private javax.swing.JButton BUbah;
     private javax.swing.JTextField JTCari;
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JScrollPane jScrollPane1;
     private F.JcomFromDBtable jcomFromDBtable1;
     private F.Jktable jktable1;
     private org.jdesktop.beansbinding.BindingGroup bindingGroup;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(MSPK.class.getName());

}
