/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import F.FLaporan;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Logger;

/**
 *
 * @author JACK
 */
public class LDOTRIP extends javax.swing.JFrame {

    /**
     * Creates new form LPermintaanKerja
     */
    public LDOTRIP() {
        initComponents();
        setTitle("Laporan Jumlah Trip Kendaraan ");
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel2 = new javax.swing.JLabel();
          JDMulai = new com.toedter.calendar.JDateChooser();
          jLabel3 = new javax.swing.JLabel();
          JDEND = new com.toedter.calendar.JDateChooser();
          jLabel5 = new javax.swing.JLabel();
          Jcomorder = new javax.swing.JComboBox();
          jButton1 = new javax.swing.JButton();
          JtextCari = new F.JackTextField();
          JcPlat = new F.JcomFromDb();
          jButton2 = new javax.swing.JButton();
          jLabel6 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setResizable(false);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mulai Tanggal ");

          JDMulai.setDate(new Date());
          JDMulai.setDateFormatString("dd/MM/yyyy");
          JDMulai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Hingga");

          JDEND.setDate(new Date());
          JDEND.setDateFormatString("dd/MM/yyyy");
          JDEND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Urut NoPolisi Mulai ");

          Jcomorder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil", "Terbesar" }));

          jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton1.setText("TAMPIL BERDASARKAN PLAT");
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          JtextCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JtextCari.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JtextCariKeyReleased(evt);
               }
          });

          JcPlat.setQuery("SELECT `NoPolisi`FROM `ttruck`");
          JcPlat.excute();
          JcPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton2.setText("TAMPIL KESELURUHAN");
          jButton2.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton2ActionPerformed(evt);
               }
          });

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Cari Plat");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(4, 4, 4)
                              .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel3)
                              .addGap(4, 4, 4)
                              .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel5)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jButton1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jButton2)))
                    .addContainerGap(62, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel6))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1)
                         .addComponent(jButton2))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JDEND, JDMulai, JcPlat, Jcomorder, JtextCari, jButton1, jButton2, jLabel2, jLabel3, jLabel5, jLabel6});

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         TAMPILL(true);
     }//GEN-LAST:event_jButton1ActionPerformed

    void TAMPILL(Boolean cariplat) {
        HashMap hashs = new HashMap();
        String Statusjcom;
        String StatusOrder;
        String Cari;
        if (Jcomorder.getSelectedIndex() == 0) {
            StatusOrder = "ASC";
        } else {
            StatusOrder = "DESC";
        }
        if (cariplat == true) {
            Cari = " and `NoPolisi` = '" + JcPlat.getSelectedItem().toString() + "'";
            hashs.put("Title2", "Plat = " + JcPlat.getSelectedItem().toString());
        } else {
            Cari = "";
            hashs.put("Title2", "");
        }
        hashs.put("Title", "Laporan Jumlah Trip Kendaraan");
        hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
        hashs.put("Where", "Where date(`TglDOKeluar`) between '" + F.Datetostringwidthformat.getstringfromdate(JDMulai.getDate(), "yyyy-MM-dd") + "' and '" + F.Datetostringwidthformat.getstringfromdate(JDEND.getDate(), "yyyy-MM-dd") + "' " + Cari + "  group by `NoPolisi` " + StatusOrder + "");
        FLaporan fLaporan = new F.FLaporan();
        fLaporan.sethashmap(hashs);
        fLaporan.setfilename("LKMTruckTrip");
        fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
        fLaporan.excute();
        F.History.STambah("LKMTruckTrip");
    }
     private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
     {//GEN-HEADEREND:event_formWindowClosing
         F.VarJFrame.LaporanLDOTRIP = null;          // TODO add your handling code here:
     }//GEN-LAST:event_formWindowClosing

     private void JtextCariKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JtextCariKeyReleased
     {//GEN-HEADEREND:event_JtextCariKeyReleased
         JcPlat.setQuery("SELECT `NoPolisi`FROM `ttruck` where `NoPolisi` like '%" + JtextCari.getText() + "%'");
         JcPlat.excute();
         JcPlat.showPopup();// TODO add your handling code here:
     }//GEN-LAST:event_JtextCariKeyReleased

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
     {//GEN-HEADEREND:event_jButton2ActionPerformed
         TAMPILL(false);       // TODO add your handling code here:
     }//GEN-LAST:event_jButton2ActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private com.toedter.calendar.JDateChooser JDEND;
     private com.toedter.calendar.JDateChooser JDMulai;
     private F.JcomFromDb JcPlat;
     private javax.swing.JComboBox Jcomorder;
     private F.JackTextField JtextCari;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(LDOTRIP.class.getName());
}
