/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import F.FLaporan;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;

/**
 *
 * @author JACK
 */
public class LKartuService extends javax.swing.JFrame {

    /**
     * Creates new form LPermintaanKerja
     */
    public LKartuService() {
        initComponents();
        setTitle("Laporan Kartu Service");
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    String SelecQ = " SELECT a.`NoOpnameSPK` as 'No Opname SPK', a.`NoPerintahKerja`as 'NoPerintahKerja' , DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i') as 'Tanggal OpnameSPK',DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i') as 'Tanggal SPK', a.`Plat`as 'Plat', a.`Sopir`as 'Sopir', IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as 'Jenis Permintaan', if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror'))) as 'Jenis Pekerjaan', if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda', if(a.`TingkatPekerjaan`=1,'Darurat','Eror')) as 'Tingkat Pekerjaan', a.`KMT` as 'KM Truck', a.`User`as 'User' ,a.`CatKhusus` as 'Catatan Khusus' FROM `tbopnamespk` a join `tbperintahkerja` b on a.`NoPerintahKerja` = b.`NoPerintahKerja`";
    String SelecQ2 = "SELECT a.`NoOpnameSPK` as 'a.`NoOpnameSPK`',a.`NoPerintahKerja` as 'a.`NoPerintahKerja`',DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i') as \"DATE_FORMAT(a.`Tgl`,'%d/%m/%Y %H:%i')\",DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i') as \"DATE_FORMAT(b.`Tgl`,'%d/%m/%Y %H:%i')\",a.`Plat` as 'a.`Plat`',a.`Sopir` as 'a.`Sopir`',IF(a.`JPermintaan` = 0,'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` =2,'Perawatan dan perbaikan','eror'))) as \"IF(a.`JPermintaan` = 0,'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror')))\",if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror'))) as \"if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror')))\",if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda',if(a.`TingkatPekerjaan`=1,'Darurat','Eror')) as \"if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda',if(a.`TingkatPekerjaan`=1,'Darurat','Eror'))\",a.`KMT` as 'a.`KMT`',a.`User` as 'a.`User`',a.`CatKhusus` as 'a.CatKhusus'FROM `tbopnamespk` a join `tbperintahkerja` b on a.`NoPerintahKerja` = b.`NoPerintahKerja`";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel2 = new javax.swing.JLabel();
          JDMulai = new com.toedter.calendar.JDateChooser();
          jLabel3 = new javax.swing.JLabel();
          JDEND = new com.toedter.calendar.JDateChooser();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          Jcomorder = new javax.swing.JComboBox();
          jButton1 = new javax.swing.JButton();
          JcomKolom = new F.JcomFromDBtable();
          jLabel6 = new javax.swing.JLabel();
          JtextCari = new F.JackTextField();
          JcPlat = new F.JcomFromDb();
          jButton2 = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setResizable(false);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mulai Tanggal ");

          JDMulai.setDate(new Date());
          JDMulai.setDateFormatString("dd/MM/yyyy");
          JDMulai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Hingga");

          JDEND.setDate(new Date());
          JDEND.setDateFormatString("dd/MM/yyyy");
          JDEND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Urut");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Berdasarkan");

          Jcomorder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil / Terbaru", "Terbesar / Terlama" }));

          jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton1.setText("Tampilkan");
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          JcomKolom.setQuery1(SelecQ);
          JcomKolom.setQuery2(SelecQ2);
          JcomKolom.excute1();
          JcomKolom.excute2();
          JcomKolom.setSelectedIndex(2);
          JcomKolom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Plat ");

          JtextCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JtextCari.addKeyListener(new java.awt.event.KeyAdapter()
          {
               public void keyReleased(java.awt.event.KeyEvent evt)
               {
                    JtextCariKeyReleased(evt);
               }
          });

          JcPlat.setQuery("SELECT `NoPolisi`FROM `ttruck`");
          JcPlat.excute();
          JcPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton2.setText("Tampilkan Semua");
          jButton2.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton2ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(4, 4, 4)
                              .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel3)
                              .addGap(4, 4, 4)
                              .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, 0)
                              .addComponent(jLabel5)
                              .addGap(4, 4, 4)
                              .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jButton1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jButton2)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel4)
                                   .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jButton1)
                         .addComponent(jButton2))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JDEND, JDMulai, JcPlat, JcomKolom, Jcomorder, JtextCari, jButton1, jButton2, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         printlaporan(true);
     }//GEN-LAST:event_jButton1ActionPerformed

    void printlaporan(boolean CARIPLAT) {
        HashMap hashs = new HashMap();
        String Statusjcom;
        String StatusOrder;
        String Cari;
        if (Jcomorder.getSelectedIndex() == 0) {
            StatusOrder = "ASC";
        } else {
            StatusOrder = "DESC";
        }
        if (CARIPLAT) {
            Cari = " and `a`.`Plat` = '" + JcPlat.getSelectedItem().toString() + "'";
            hashs.put("Title2", "Plat = " + JcPlat.getSelectedItem().toString());
        } else {
            Cari = "";
            hashs.put("Title2", "");
        }
        hashs.put("Title", "Kartu Service");
        hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
        Vector v = JcomKolom.getcoloumname();
        hashs.put("Where", "Where date(a.`Tgl`) between '" + F.Datetostringwidthformat.getstringfromdate(JDMulai.getDate(), "yyyy-MM-dd") + "' and '" + F.Datetostringwidthformat.getstringfromdate(JDEND.getDate(), "yyyy-MM-dd") + "' " + Cari + " Order By " + v.get(JcomKolom.getSelectedIndex()) + " " + StatusOrder);
        FLaporan fLaporan = new F.FLaporan();
        fLaporan.sethashmap(hashs);
        fLaporan.setfilename("LKartuService");
        fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
        fLaporan.excute();
        F.History.STambah("LkartuServices");
    }
     private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
     {//GEN-HEADEREND:event_formWindowClosing
         F.VarJFrame.lKartuService = null;          // TODO add your handling code here:
     }//GEN-LAST:event_formWindowClosing

     private void JtextCariKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JtextCariKeyReleased
     {//GEN-HEADEREND:event_JtextCariKeyReleased
         JcPlat.setQuery("SELECT `NoPolisi`FROM `ttruck` where `NoPolisi` like '%" + JtextCari.getText() + "%'");
         JcPlat.excute();
         JcPlat.showPopup();// TODO add your handling code here:
     }//GEN-LAST:event_JtextCariKeyReleased

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
     {//GEN-HEADEREND:event_jButton2ActionPerformed
         printlaporan(false);     // TODO add your handling code here:
     }//GEN-LAST:event_jButton2ActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private com.toedter.calendar.JDateChooser JDEND;
     private com.toedter.calendar.JDateChooser JDMulai;
     private F.JcomFromDb JcPlat;
     private F.JcomFromDBtable JcomKolom;
     private javax.swing.JComboBox Jcomorder;
     private F.JackTextField JtextCari;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(LKartuService.class.getName());
}
