/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import F.FLaporan;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;

/**
 *
 * @author JACK
 */
public class LMaster extends javax.swing.JFrame {

    /**
     * Creates new form LPermintaanKerja
     */
    public LMaster() {
        initComponents();
        setTitle("Laporan Master");
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    String SelecQ = " SELECT `AliasPKS`, `NamaPKS`, `AlamatPKS` FROM `tpks`";
    String SelecQ1 = "SELECT `AliasPKS`, `NamaPKS`, `AlamatPKS` FROM `tpks`";
    String SelecQ2 = "SELECT `NoPolisi`, `KMO`,`Stat` FROM `ttruck`";
    String SelecQ3 = "SELECT `NoPolisi`, `KMO`,`Stat` FROM `ttruck`";
    String SelecQ4 = "SELECT `Jenis Service`, `Keterangan` FROM `tjenisservice`";
    String SelecQ5 = "SELECT `Jenis Service`, `Keterangan` FROM `tjenisservice`";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel1 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          Jcomorder = new javax.swing.JComboBox();
          jButton1 = new javax.swing.JButton();
          JcomKolom = new F.JcomFromDBtable();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          Jcomorder1 = new javax.swing.JComboBox();
          jButton2 = new javax.swing.JButton();
          JcomKolom1 = new F.JcomFromDBtable();
          jLabel2 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jLabel9 = new javax.swing.JLabel();
          Jcomorder2 = new javax.swing.JComboBox();
          jButton3 = new javax.swing.JButton();
          JcomKolom2 = new F.JcomFromDBtable();
          jLabel3 = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setResizable(false);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel1.setText("Master PKS");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Urut");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Berdasarkan");

          Jcomorder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil / Terbaru", "Terbesar / Terlama" }));

          jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton1.setText("Tampil Master PKS");
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          JcomKolom.setQuery1(SelecQ);
          JcomKolom.setQuery2(SelecQ1);
          JcomKolom.excute1();
          JcomKolom.excute2();
          JcomKolom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Urut");

          jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel7.setText("Berdasarkan");

          Jcomorder1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil / Terbaru", "Terbesar / Terlama" }));

          jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton2.setText("Tampil Master Truck");
          jButton2.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton2ActionPerformed(evt);
               }
          });

          JcomKolom1.setQuery1(SelecQ2);
          JcomKolom1.setQuery2(SelecQ3);
          JcomKolom1.excute1();
          JcomKolom1.excute2();
          JcomKolom1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Master Truck");

          jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel8.setText("Urut");

          jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel9.setText("Berdasarkan");

          Jcomorder2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil / Terbaru", "Terbesar / Terlama" }));

          jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton3.setText("Tampil Jenis Service");
          jButton3.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton3ActionPerformed(evt);
               }
          });

          JcomKolom2.setQuery1(SelecQ4);
          JcomKolom2.setQuery2(SelecQ5);
          JcomKolom2.excute1();
          JcomKolom2.excute2();
          JcomKolom2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Master Jenis Service");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel5)
                              .addGap(4, 4, 4)
                              .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jButton1)
                         .addComponent(jLabel2)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcomKolom1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel7)
                              .addGap(4, 4, 4)
                              .addComponent(Jcomorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jButton2)
                         .addComponent(jLabel3)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel8)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcomKolom2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel9)
                              .addGap(4, 4, 4)
                              .addComponent(Jcomorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jButton3))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel1)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel4)
                                   .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))))
                    .addGap(11, 11, 11)
                    .addComponent(jButton1)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel2)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Jcomorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel6)
                                   .addComponent(JcomKolom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel7))))
                    .addGap(11, 11, 11)
                    .addComponent(jButton2)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel3)
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Jcomorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel8)
                                   .addComponent(JcomKolom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel9))))
                    .addGap(11, 11, 11)
                    .addComponent(jButton3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JcomKolom, JcomKolom1, JcomKolom2, Jcomorder, Jcomorder1, Jcomorder2, jButton1, jButton2, jButton3, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         if (Jcomorder.getSelectedIndex() == 0) {
             StatusOrder = "ASC";
         } else {
             StatusOrder = "DESC";
         }
         hashs.put("Title", "Master PKS");
         hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
         Vector v = JcomKolom.getcoloumname();
         hashs.put("Where", " Order By `" + v.get(JcomKolom.getSelectedIndex()) + "` " + StatusOrder);
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("MPKS");
         fLaporan.setErorm("Gagal Menampilkan Master PKS");
         fLaporan.excute();
         F.History.STambah("MPKS");
     }//GEN-LAST:event_jButton1ActionPerformed

     private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
     {//GEN-HEADEREND:event_formWindowClosing
         F.VarJFrame.laporanMaster = null;          // TODO add your handling code here:
     }//GEN-LAST:event_formWindowClosing

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
     {//GEN-HEADEREND:event_jButton2ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         if (Jcomorder1.getSelectedIndex() == 0) {
             StatusOrder = " ASC ";
         } else {
             StatusOrder = " DESC ";
         }
         hashs.put("Title", "Master Truck");
         hashs.put("PrintedBy", " Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm") + " ");
         Vector v = JcomKolom1.getcoloumname();
         hashs.put("Where", " Order By `" + v.get(JcomKolom1.getSelectedIndex()) + "` " + StatusOrder + " ");
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("MTruck");
         fLaporan.setErorm("Gagal Menampilkan Master Truck");
         fLaporan.excute();
         F.History.STambah("MTruck");
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
     {//GEN-HEADEREND:event_jButton3ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         if (Jcomorder2.getSelectedIndex() == 0) {
             StatusOrder = " ASC ";
         } else {
             StatusOrder = " DESC ";
         }
         hashs.put("Title", "Master Jenis Service");
         hashs.put("PrintedBy", " Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm") + " ");
         Vector v = JcomKolom2.getcoloumname();
         hashs.put("Where", " Order By `" + v.get(JcomKolom2.getSelectedIndex()) + "` " + StatusOrder + " ");
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("MJenisService");
         fLaporan.setErorm("Gagal Menampilkan MasterJenis Service");
         fLaporan.excute();
         F.History.STambah("MJenisService");
     }//GEN-LAST:event_jButton3ActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private F.JcomFromDBtable JcomKolom;
     private F.JcomFromDBtable JcomKolom1;
     private F.JcomFromDBtable JcomKolom2;
     private javax.swing.JComboBox Jcomorder;
     private javax.swing.JComboBox Jcomorder1;
     private javax.swing.JComboBox Jcomorder2;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(LMaster.class.getName());
}
