/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Laporan;

import F.FLaporan;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Logger;

/**
 *
 * @author JACK
 */
public class LSPK extends javax.swing.JFrame {

    /**
     * Creates new form LPermintaanKerja
     */
    public LSPK() {
        initComponents();
        setTitle("Laporan Perintah Kerja");
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    String SelecQ = "SELECT `NoPermintaan` as 'NoPermintaan',  DATE_FORMAT(`Tgl`,'%d/%m/%Y %H:%i') as 'Tanggal', `Plat` as 'Plat', `Sopir` as 'Sopir', IF(`JPermintaan` = 0, 'Perawatan',if(`JPermintaan` = 1,'Perbaikan',if(`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as 'Jenis Permintaan', if(`JPekerjaan`=0,'Kecil',if(`JPekerjaan`=1,'Sedang', if(`JPekerjaan`=2,'Besar','Eror'))) as 'Jenis Pekerjaan', if(`TingkatPekerjaan`=0,'Dapat Di Tunda', if(`TingkatPekerjaan`=1,'Darurat','Eror')) as 'Tingkat Pekerjaan', `KMT` as 'KM Truck', `User` as 'User' FROM `tbpermintaan`  ";
    String SelecQ2 = "SELECT a.`NoPermintaan`as 'a.`NoPermintaan`',a.`Tgl` as 'a.`Tgl`',a.`Plat` as 'a.`Plat`',a.`Sopir` as 'a.`Sopir`', IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror'))) as \"IF(a.`JPermintaan` = 0, 'Perawatan',if(a.`JPermintaan` = 1,'Perbaikan',if(a.`JPermintaan` = 2,'Perawatan dan perbaikan','eror')))\",If(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror'))) as \"if(a.`JPekerjaan`=0,'Kecil',if(a.`JPekerjaan`=1,'Sedang', if(a.`JPekerjaan`=2,'Besar','Eror')))\",if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda',if(a.`TingkatPekerjaan`=1,'Darurat','Eror')) as \"if(a.`TingkatPekerjaan`=0,'Dapat Di Tunda',if(a.`TingkatPekerjaan`=1,'Darurat','Eror'))\",a.`KMT` as 'a.`KMT`',a.`User` as 'a.`User`'FROM `tbpermintaan` a left join `tbperintahkerja` b on a.`NoPermintaan`=b.`NoPermintaan`";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          buttonGroup2 = new javax.swing.ButtonGroup();
          jLabel2 = new javax.swing.JLabel();
          JDMulai = new com.toedter.calendar.JDateChooser();
          jLabel3 = new javax.swing.JLabel();
          JDEND = new com.toedter.calendar.JDateChooser();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          Jcomorder = new javax.swing.JComboBox();
          jButton1 = new javax.swing.JButton();
          JcomKolom = new F.JcomFromDBtable();
          JRSmua = new javax.swing.JRadioButton();
          JRNOOSPK = new javax.swing.JRadioButton();
          JRONLYOSPK = new javax.swing.JRadioButton();
          jLabel6 = new javax.swing.JLabel();
          JcColomCari = new F.JcomFromDBtable();
          jLabel7 = new javax.swing.JLabel();
          JtextCari = new F.JackTextField();

          buttonGroup2.add(JRSmua);
          buttonGroup2.add(JRNOOSPK);
          buttonGroup2.add(JRONLYOSPK);

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setResizable(false);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("Mulai Tanggal ");

          JDMulai.setDate(new Date());
          JDMulai.setDateFormatString("dd/MM/yyyy");
          JDMulai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Hingga");

          JDEND.setDate(new Date());
          JDEND.setDateFormatString("dd/MM/yyyy");
          JDEND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("Urut");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("Berdasarkan");

          Jcomorder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          Jcomorder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terkecil / Terbaru", "Terbesar / Terlama" }));

          jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jButton1.setText("Tampil");
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          JcomKolom.setQuery1(SelecQ);
          JcomKolom.setQuery2(SelecQ2);
          JcomKolom.excute1();
          JcomKolom.excute2();
          JcomKolom.setSelectedIndex(1);
          JcomKolom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JRSmua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JRSmua.setSelected(true);
          JRSmua.setText("Semua");

          JRNOOSPK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JRNOOSPK.setText("Yang Belum Memiliki Opname");

          JRONLYOSPK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JRONLYOSPK.setText("Yang Sudah Memiliki Opname");

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("Tampilkan Hanya ");

          JcColomCari.setQuery1(SelecQ);
          JcColomCari.setQuery2(SelecQ2);
          JcColomCari.excute1();
          JcColomCari.excute2();
          JcColomCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel7.setText("=");

          JtextCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addGap(4, 4, 4)
                              .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel3)
                              .addGap(4, 4, 4)
                              .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(4, 4, 4)
                              .addComponent(jLabel5)
                              .addGap(4, 4, 4)
                              .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel6)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JcColomCari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel7)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(JRSmua)
                         .addComponent(JRNOOSPK)
                         .addComponent(JRONLYOSPK)
                         .addComponent(jButton1))
                    .addContainerGap(75, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JDEND, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(Jcomorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(3, 3, 3)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel4)
                                   .addComponent(JcomKolom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel7)
                         .addComponent(JcColomCari, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(JtextCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(JRSmua)
                    .addGap(2, 2, 2)
                    .addComponent(JRNOOSPK)
                    .addGap(0, 0, 0)
                    .addComponent(JRONLYOSPK)
                    .addGap(2, 2, 2)
                    .addComponent(jButton1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JDEND, JDMulai, JRNOOSPK, JRONLYOSPK, JRSmua, JcColomCari, JcomKolom, Jcomorder, JtextCari, jButton1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

          JRSmua.getAccessibleContext().setAccessibleDescription("");

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
     {//GEN-HEADEREND:event_jButton1ActionPerformed
         HashMap hashs = new HashMap();
         String Statusjcom;
         String StatusOrder;
         String Cari;
         if (Jcomorder.getSelectedIndex() == 0) {
             StatusOrder = "ASC";
         } else {
             StatusOrder = "DESC";
         }
         if (JRSmua.isSelected()) {
             hashs.put("Title", "LAPORAN SPK");
             Statusjcom = "";
         } else if (JRNOOSPK.isSelected()) {
             hashs.put("Title", "LAPORAN SPK BELUM OPNAME");
             Statusjcom = "and  b.`NoPerintahKerja` is null ";
         } else if (JRONLYOSPK.isSelected()) {
             hashs.put("Title", "LAPORAN SPK SUDAH OPNAME");
             Statusjcom = "and b.`NoPerintahKerja` is not null ";
         } else {
             hashs.put("Title", "Eror");
             Statusjcom = "";
         }
         if (!JtextCari.getText().isEmpty()) {
             Vector x = JcColomCari.getcoloumname();
             Cari = " and " + x.get(JcColomCari.getSelectedIndex()) + " = '" + JtextCari.getText() + "'";
         } else {
             Cari = "";
         }
         hashs.put("Title2", "Periode " + F.Datetostringwidthformat.getstringfromdate(JDMulai.getDate(), "dd/MM/yyyy") + " Hingga " + F.Datetostringwidthformat.getstringfromdate(JDEND.getDate(), "dd/MM/yyyy"));
         hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
         Vector v = JcomKolom.getcoloumname();
         hashs.put("Where", "Where date(a.`Tgl`) between '" + F.Datetostringwidthformat.getstringfromdate(JDMulai.getDate(), "yyyy-MM-dd") + "' and '" + F.Datetostringwidthformat.getstringfromdate(JDEND.getDate(), "yyyy-MM-dd") + "' " + Cari + " " + Statusjcom + " Order By " + v.get(JcomKolom.getSelectedIndex()) + " " + StatusOrder);
         FLaporan fLaporan = new F.FLaporan();
         fLaporan.sethashmap(hashs);
         fLaporan.setfilename("LSPK");
         fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
         fLaporan.excute();
         F.History.STambah("LSPK");
     }//GEN-LAST:event_jButton1ActionPerformed

     private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
     {//GEN-HEADEREND:event_formWindowClosing
         F.VarJFrame.lPerintahKerja = null;          // TODO add your handling code here:
     }//GEN-LAST:event_formWindowClosing

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private com.toedter.calendar.JDateChooser JDEND;
     private com.toedter.calendar.JDateChooser JDMulai;
     private javax.swing.JRadioButton JRNOOSPK;
     private javax.swing.JRadioButton JRONLYOSPK;
     private javax.swing.JRadioButton JRSmua;
     private F.JcomFromDBtable JcColomCari;
     private F.JcomFromDBtable JcomKolom;
     private javax.swing.JComboBox Jcomorder;
     private F.JackTextField JtextCari;
     private javax.swing.ButtonGroup buttonGroup2;
     private javax.swing.JButton jButton1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(LSPK.class.getName());
}
