/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses.WOpSPK;

import static F.Datetostringwidthformat.getstringfromdate;
import F.FLaporan;
import static F.GenNoPermintaan.GenNoStockOpname;
import static F.GenNoPermintaan.GetNoPerintahKerja;
import F.RunMultiUpd;
import F.RunSelct2;
import F.RunUpd;
import static F.VarJFrame.tambahOpnameSPK;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JACK
 */
public class TambahOSPK extends javax.swing.JFrame {

    /**
     * Creates new form Serivice
     */
    public TambahOSPK() {
        initComponents();
        setTitle("Tambah Opname SPK");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        JTNoOpnameSPK.setText(GenNoStockOpname());
        getdata(JtNoPermintaanKerja.getSelectedItem().toString());
        setVisible(true);
    }
    String QJcP1 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=2 order by `NoCol`";
    String QJcP2 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=3 order by `NoCol`";
    String QJcP3 = "SELECT `VarPar` FROM `tbseting` WHERE `KSet`=4 order by `NoCol`";

    void getSelectedData() {
        if (JTable.getSelectedRow() != -1) {
            int row = JTable.getSelectedRow();
        }
    }

    /**
     *
     * @param table
     * @return
     */
    public Object[][] getTableData(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = dtm.getValueAt(i, j);
            }
        }
        return tableData;
    }

    private void getdata(String NoPerintahKerja) {
        RunSelct2 runSelct2 = new F.RunSelct2();
        runSelct2.setQuery("SELECT `No`, `NoPerintahKerja`, `NoPermintaan`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`FROM `tbperintahkerja` WHERE `NoPerintahKerja` ='" + NoPerintahKerja + "'");
        try {
            ResultSet rs = runSelct2.excute();
            if (!rs.isBeforeFirst()) {
                JcPlat.setText("");
                JtSopir.setText("");
                JcPemintaan.setSelectedIndex(0);
                JcPerbaikan.setSelectedIndex(0);
                JcPrioritas.setSelectedIndex(0);
                JTKMMobil.setInt(0);
                JTCatatanKhusus.setText("");
            }
            while (rs.next()) {
                JcCariKaMekanik.setText("");
                JcCariMekanik.setText("");
                JcPlat.setText(rs.getString("Plat"));
                JtSopir.setText(rs.getString("Sopir"));
                JcPemintaan.setSelectedIndex(rs.getInt("JPermintaan"));
                JcPerbaikan.setSelectedIndex(rs.getInt("JPekerjaan"));
                JcPrioritas.setSelectedIndex(rs.getInt("TingkatPekerjaan"));
                JTKMMobil.setInt(rs.getInt("KMT"));
                JTCatatanKhusus.setText(rs.getString("CatKhusus"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "gagal Menampilkan Data");
            e.printStackTrace();
        } finally {
            runSelct2.closecon();
        }
        JTable.setQuery("SELECT `NoCol` as 'No', `JenisPermintaan` as 'Jenis Permintaan', `Keterangan` as 'Keterangan', `Ongkos` as 'OngkosServices',false as 'Selesai' FROM `tbdetailperintahkerja` WHERE `NoPerintahKerja` = '" + NoPerintahKerja + "' order by `No` Asc");
        JTable.useboolean(true);
        JTable.seteditable(3);
        JTable.setbooleanfield(4);
        JTable.tampilkan();
        JTable1.setQuery("SELECT `NoCol`, `KodeBarang`, `DeskripsiBarang`, `Jumlah`, `Satuan`,false as 'Selesai' FROM `tbpermintaanbarang` a join `tbdetailpermintaanbarang` b on a.NoPermintaanBarang = b.NoPermintaanBarang WHERE `NoPerintahKerja` = '" + NoPerintahKerja + "' order by b.`NoCol` Asc");
        JTable1.useboolean(true);
        JTable1.setbooleanfield(5);
        JTable1.tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents()
     {

          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          JdTGL = new com.toedter.calendar.JDateChooser();
          jButton1 = new javax.swing.JButton();
          jLabel17 = new javax.swing.JLabel();
          jLabel18 = new javax.swing.JLabel();
          jLabel21 = new javax.swing.JLabel();
          jLabel22 = new javax.swing.JLabel();
          jLabel23 = new javax.swing.JLabel();
          jLabel24 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          JcPemintaan = new F.JcomFromDb();
          JcPerbaikan = new F.JcomFromDb();
          JcPrioritas = new F.JcomFromDb();
          jLabel6 = new javax.swing.JLabel();
          JtNoPermintaanKerja = new F.JcomFromDb();
          JTNoOpnameSPK = new F.JackTextField();
          jLabel1 = new javax.swing.JLabel();
          jScrollPane2 = new javax.swing.JScrollPane();
          JTable = new F.Jktable();
          jScrollPane3 = new javax.swing.JScrollPane();
          JTable1 = new F.Jktable();
          JTKMMobil = new F.RibuanTextField();
          JcPlat = new F.JackTextField();
          JtCariPermintaan = new F.JackTextField();
          JtSopir = new F.JackTextField();
          jtUser = new F.JackTextField();
          JTTime = new javax.swing.JFormattedTextField();
          jLabel19 = new javax.swing.JLabel();
          JTCatatanKhusus = new F.JackTextField();
          jButton2 = new javax.swing.JButton();
          jButton3 = new javax.swing.JButton();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          JcKaMekanik = new F.JcomFromDb();
          JcCariMekanik = new F.JKTextfield();
          JcCariKaMekanik = new F.JKTextfield();
          JcMekanik = new F.JcomFromDb();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter()
          {
               public void windowClosing(java.awt.event.WindowEvent evt)
               {
                    formWindowClosing(evt);
               }
          });

          jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel2.setText("PLAT");

          jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel3.setText("Waktu & Tanggal");

          jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel4.setText("No SPK");

          JdTGL.setDate(new Date());
          JdTGL.setDateFormatString("dd-MM-yyyy");
          JdTGL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jButton1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jButton1.setText("SIMPAN");
          jButton1.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel17.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
          jLabel17.setText("USER :");

          jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

          jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel21.setText("SOPIR");

          jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel22.setText("Jenis Permintaan");

          jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel23.setText("Jenis Perbaikan");

          jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel24.setText("Prioritas Perbaikan");

          jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel5.setText("KM Mobil");

          JcPemintaan.setQuery(QJcP1);
          JcPemintaan.setaawalkosong(false);
          JcPemintaan.excute();
          JcPemintaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JcPerbaikan.setQuery(QJcP2);
          JcPerbaikan.setaawalkosong(false);
          JcPerbaikan.excute();
          JcPerbaikan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          JcPrioritas.setQuery(QJcP3);
          JcPrioritas.setaawalkosong(false);
          JcPrioritas.excute();
          JcPrioritas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel6.setText("No OSPK");

          JtNoPermintaanKerja.setQuery("SELECT a.`NoPerintahKerja` FROM `tbperintahkerja` a left join `tbopnamespk` b on a.NoPerintahKerja = b.`NoPerintahKerja` where b.`NoPerintahKerja` is null");
          JtNoPermintaanKerja.excute();
          JtNoPermintaanKerja.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          JtNoPermintaanKerja.addItemListener(new java.awt.event.ItemListener()
          {
               public void itemStateChanged(java.awt.event.ItemEvent evt)
               {
                    JtNoPermintaanKerjaItemStateChanged(evt);
               }
          });
          JtNoPermintaanKerja.addActionListener(new java.awt.event.ActionListener()
          {
               public void actionPerformed(java.awt.event.ActionEvent evt)
               {
                    JtNoPermintaanKerjaActionPerformed(evt);
               }
          });

          JTNoOpnameSPK.setDisabledTextColor(new java.awt.Color(0, 0, 102));
          JTNoOpnameSPK.setEnabled(false);
          JTNoOpnameSPK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

          jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
          jLabel1.setText("Cari Permintaan :");

          JTable.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][]
               {

               },
               new String []
               {
                    "No", "Jenis Service", "Keterangan", "Ongkos Service", "Selesai"
               }
          )
          {
               Class[] types = new Class []
               {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
               };
               boolean[] canEdit = new boolean []
               {
                    false, false, false, true, true
               };

               public Class getColumnClass(int columnIndex)
               {
                    return types [columnIndex];
               }

               public boolean isCellEditable(int rowIndex, int columnIndex)
               {
                    return canEdit [columnIndex];
               }
          });
          JTable.getSelectionModel().addListSelectionListener(new
               ListSelectionListener()
               {
                    public void valueChanged(ListSelectionEvent e)
                    {
                         getSelectedData();
                    }
               });
               jScrollPane2.setViewportView(JTable);

               JTable1.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][]
                    {

                    },
                    new String []
                    {
                         "No", "Jenis Service", "Keterangan", "Ongkos Service", "Di Gunakan"
                    }
               )
               {
                    Class[] types = new Class []
                    {
                         java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
                    };
                    boolean[] canEdit = new boolean []
                    {
                         false, false, false, false, true
                    };

                    public Class getColumnClass(int columnIndex)
                    {
                         return types [columnIndex];
                    }

                    public boolean isCellEditable(int rowIndex, int columnIndex)
                    {
                         return canEdit [columnIndex];
                    }
               });
               JTable1.getSelectionModel().addListSelectionListener(new
                    ListSelectionListener()
                    {
                         public void valueChanged(ListSelectionEvent e)
                         {
                              getSelectedData();
                         }
                    });
                    jScrollPane3.setViewportView(JTable1);

                    JTKMMobil.setText("0");
                    JTKMMobil.setDisabledTextColor(new java.awt.Color(0, 0, 102));
                    JTKMMobil.setEnabled(false);
                    JTKMMobil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    JcPlat.setDisabledTextColor(new java.awt.Color(0, 0, 102));
                    JcPlat.setEnabled(false);
                    JcPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    JtCariPermintaan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    JtCariPermintaan.addKeyListener(new java.awt.event.KeyAdapter()
                    {
                         public void keyReleased(java.awt.event.KeyEvent evt)
                         {
                              JtCariPermintaanKeyReleased(evt);
                         }
                    });

                    JtSopir.setEnabled(false);
                    JtSopir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    jtUser.setText(F.Variablebanking.SUsername);
                    jtUser.setEnabled(false);
                    jtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    JTTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
                    JTTime.setText(F.Datetostringwidthformat.getstringfromdate(new Date(),"HH:mm"));
                    JTTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    jLabel19.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                    jLabel19.setText("Catatan Khusus :");

                    JTCatatanKhusus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

                    jButton2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                    jButton2.setText("SIMPAN DAN BARU");
                    jButton2.setName(""); // NOI18N
                    jButton2.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              jButton2ActionPerformed(evt);
                         }
                    });

                    jButton3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
                    jButton3.setText("CETAK");
                    jButton3.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              jButton3ActionPerformed(evt);
                         }
                    });

                    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    jLabel7.setText("KA Mekanik");

                    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    jLabel8.setText("Mekanik");

                    JcKaMekanik.setQuery("SELECT `Nama` FROM `tbkamekanik` WHERE Status = 0");
                    JcKaMekanik.excute();
                    JcKaMekanik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    JcKaMekanik.addItemListener(new java.awt.event.ItemListener()
                    {
                         public void itemStateChanged(java.awt.event.ItemEvent evt)
                         {
                              JcKaMekanikItemStateChanged(evt);
                         }
                    });
                    JcKaMekanik.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              JcKaMekanikActionPerformed(evt);
                         }
                    });

                    JcCariMekanik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    JcCariMekanik.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              JcCariMekanikActionPerformed(evt);
                         }
                    });
                    JcCariMekanik.addKeyListener(new java.awt.event.KeyAdapter()
                    {
                         public void keyReleased(java.awt.event.KeyEvent evt)
                         {
                              JcCariMekanikKeyReleased(evt);
                         }
                    });

                    JcCariKaMekanik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    JcCariKaMekanik.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              JcCariKaMekanikActionPerformed(evt);
                         }
                    });
                    JcCariKaMekanik.addKeyListener(new java.awt.event.KeyAdapter()
                    {
                         public void keyReleased(java.awt.event.KeyEvent evt)
                         {
                              JcCariKaMekanikKeyReleased(evt);
                         }
                    });

                    JcMekanik.setQuery("SELECT `Nama` FROM `tbmekanik` WHERE Status = 0");
                    JcMekanik.excute();
                    JcMekanik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                    JcMekanik.addItemListener(new java.awt.event.ItemListener()
                    {
                         public void itemStateChanged(java.awt.event.ItemEvent evt)
                         {
                              JcMekanikItemStateChanged(evt);
                         }
                    });
                    JcMekanik.addActionListener(new java.awt.event.ActionListener()
                    {
                         public void actionPerformed(java.awt.event.ActionEvent evt)
                         {
                              JcMekanikActionPerformed(evt);
                         }
                    });

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jScrollPane3)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JtSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JcPemintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JcPerbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JcPrioritas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(4, 4, 4)
                                                            .addComponent(JTKMMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                       .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                 .addGroup(layout.createSequentialGroup()
                                                                      .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addGap(4, 4, 4)
                                                                      .addComponent(JdTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                 .addGroup(layout.createSequentialGroup()
                                                                      .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                      .addComponent(JcCariMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                 .addGroup(layout.createSequentialGroup()
                                                                      .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                      .addComponent(JcCariKaMekanik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addComponent(JcKaMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(JTTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addComponent(JcMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                  .addGap(0, 372, Short.MAX_VALUE))
                                             .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel17)
                                                  .addGap(4, 4, 4)
                                                  .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jButton3)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(jButton2)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(jButton1))
                                             .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(jLabel1)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(JtCariPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(JtNoPermintaanKerja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jLabel6)
                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                  .addComponent(JTNoOpnameSPK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JTCatatanKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap())
                    );
                    layout.setVerticalGroup(
                         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(9, 9, 9)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel4)
                                   .addComponent(jLabel1)
                                   .addComponent(JtCariPermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(JtNoPermintaanKerja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(JTNoOpnameSPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel6))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3))
                                   .addComponent(JTTime)
                                   .addComponent(JdTGL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                              .addGap(8, 8, 8)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel2))
                                   .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(6, 6, 6)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel21))
                                   .addComponent(JtSopir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(6, 6, 6)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel22))
                                   .addComponent(JcPemintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(6, 6, 6)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel23))
                                   .addComponent(JcPerbaikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(6, 6, 6)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel24))
                                   .addComponent(JcPrioritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(6, 6, 6)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel5))
                                   .addComponent(JTKMMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel7)
                                   .addComponent(JcKaMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(JcCariKaMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel8)
                                   .addComponent(JcCariMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(JcMekanik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(JTCatatanKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel19))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1))
                                   .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(13, 13, 13))
                    );

                    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {JTCatatanKhusus, JTKMMobil, JTNoOpnameSPK, JTTime, JcCariKaMekanik, JcCariMekanik, JcKaMekanik, JcMekanik, JcPemintaan, JcPerbaikan, JcPlat, JcPrioritas, JdTGL, JtCariPermintaan, JtNoPermintaanKerja, JtSopir, jButton1, jButton2, jButton3, jLabel1, jLabel17, jLabel19, jLabel2, jLabel21, jLabel22, jLabel23, jLabel24, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jtUser});

                    jLabel2.getAccessibleContext().setAccessibleName("150");
                    jLabel3.getAccessibleContext().setAccessibleName("150");
                    jLabel4.getAccessibleContext().setAccessibleName("150");
                    jLabel21.getAccessibleContext().setAccessibleName("150");
                    jLabel22.getAccessibleContext().setAccessibleName("150");
                    jLabel23.getAccessibleContext().setAccessibleName("150");
                    jLabel24.getAccessibleContext().setAccessibleName("150");
                    jLabel5.getAccessibleContext().setAccessibleName("150");
                    jLabel6.getAccessibleContext().setAccessibleName("150");

                    pack();
               }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTNoOpnameSPK.setText(GenNoStockOpname());
        List<String> list = new ArrayList<>();
        list.add("INSERT INTO `tbopnamespk`(`NoOpnameSPK`, `NoPerintahKerja`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`,`KaMekanik`, `Mekanik`) VALUES ("
                + "'" + JTNoOpnameSPK.getText() + "','" + JtNoPermintaanKerja.getSelectedItem().toString() + "','" + getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                + "','" + JcPlat.getText() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                + ",'" + JTKMMobil.getInt() + "','" + jtUser.getText() + "','" + JTCatatanKhusus.getText() + "','" + JcKaMekanik.getSelectedItem() + "','" + JcMekanik.getSelectedItem() + "')");
        Object[][] b = getTableData(JTable);
        for (Object[] b1 : b) {
            String bb = "";
            for (int j = 0; j <= b1.length; j++) {
                if (j == b1.length) {
                    bb += "'" + JTNoOpnameSPK.getText() + "'";
                } else if ((j == b1.length - 1) || (j == b1.length - 2) || (j == b1.length - 5)) {
                    bb += "" + b1[j] + ",";
                } else {
                    bb += "'" + b1[j] + "',";
                }
            }
            list.add("INSERT INTO `tbdetailopnamespk`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`Status`,`NoOpnameSPK`) VALUES (" + bb + ")");
        }
        Object[][] c = getTableData(JTable1);

        for (int i = 0; i < c.length; i++) {
            String cc = "";
            for (int j = 0; j < c[i].length + 1; j++) {
                if (j == c[i].length) {
                    cc += "'" + JTNoOpnameSPK.getText() + "'";
                } else if ((j == c[i].length - 2) || (j == c[i].length - 7) || (j == c[i].length - 1)) {
                    cc += "" + c[i][j] + ",";
                } else {
                    cc += "'" + c[i][j] + "',";
                }
            }
            list.add("INSERT INTO `tbdetailopnamespk2`(`NoCol`, `KodeBarang`, `DeskripsiBarang`, `Jumlah`, `Satuan`,`Status`,`NoOpnameSPK`) VALUES (" + cc + ")");
        }
        //
        for (int i = 0; i < b.length; i++) {
            if (b[i][1].equals("GANTI OLI MESIN")) {
                list.add("UPDATE `ttruck` SET `KMO`='" + 0 + "' WHERE `NoPolisi` = '" + JcPlat.getText() + "'");
            }
        }
        //
        RunMultiUpd runMultiUpd = new F.RunMultiUpd();
        runMultiUpd.setQuery(list);
        runMultiUpd.seterorm("Gagal Tambah Data !");
        int no = runMultiUpd.excute();
        if (no != 0) {
            showMessageDialog(this, "Berhasil Tambah Data");
            F.History.STambah("Tambah Data OSPK " + JTNoOpnameSPK.getText());
            F.VarJFrame.menuOpnameSPK.refresh();
            tambahOpnameSPK.dispose();
            tambahOpnameSPK = null;

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        tambahOpnameSPK = null;
        if (F.VarJFrame.menuOpnameSPK != null) {
            F.VarJFrame.menuOpnameSPK.refresh();
        }
    }//GEN-LAST:event_formWindowClosing

    private void JtNoPermintaanKerjaItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_JtNoPermintaanKerjaItemStateChanged
    {//GEN-HEADEREND:event_JtNoPermintaanKerjaItemStateChanged
        getdata(JtNoPermintaanKerja.getSelectedItem().toString());
        JTNoOpnameSPK.setText(GetNoPerintahKerja(JcPerbaikan.getSelectedIndex()));
    }//GEN-LAST:event_JtNoPermintaanKerjaItemStateChanged

    private void JtNoPermintaanKerjaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JtNoPermintaanKerjaActionPerformed
    {//GEN-HEADEREND:event_JtNoPermintaanKerjaActionPerformed
        getdata(JtNoPermintaanKerja.getSelectedItem().toString());
        JTNoOpnameSPK.setText(GetNoPerintahKerja(JcPerbaikan.getSelectedIndex()));        // TODO add your handling code here:
    }//GEN-LAST:event_JtNoPermintaanKerjaActionPerformed

     private void JtCariPermintaanKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JtCariPermintaanKeyReleased
     {//GEN-HEADEREND:event_JtCariPermintaanKeyReleased
         if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
             JdTGL.requestFocusInWindow();
         } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && JtNoPermintaanKerja.getSelectedIndex() != -1) {
             JtNoPermintaanKerja.hidePopup();
             getdata(JtNoPermintaanKerja.getSelectedItem().toString());
             JdTGL.requestFocusInWindow();
         } else {
             JtNoPermintaanKerja.setQuery("SELECT a.`NoPerintahKerja` FROM `tbperintahkerja` a left join `tbopnamespk` b on a.NoPerintahKerja = b.`NoPerintahKerja` where b.`NoPerintahKerja` is null and  a.`NoPerintahKerja` like '%" + JtCariPermintaan.getText() + "%'");
             JtNoPermintaanKerja.setaawalkosong(false);
             JtNoPermintaanKerja.excute();
             JtNoPermintaanKerja.showPopup();
         }
// TODO add your handling code here:
     }//GEN-LAST:event_JtCariPermintaanKeyReleased

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
     {//GEN-HEADEREND:event_jButton2ActionPerformed

         JTNoOpnameSPK.setText(GenNoStockOpname());
         List<String> list = new ArrayList<>();
         list.add("INSERT INTO `tbopnamespk`(`NoOpnameSPK`, `NoPerintahKerja`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`,`KaMekanik`, `Mekanik`) VALUES ("
                 + "'" + JTNoOpnameSPK.getText() + "','" + JtNoPermintaanKerja.getSelectedItem().toString() + "','" + getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                 + "','" + JcPlat.getText() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                 + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                 + ",'" + JTKMMobil.getInt() + "','" + jtUser.getText() + "','" + JTCatatanKhusus.getText() + "','" + JcKaMekanik.getSelectedItem() + "','" + JcMekanik.getSelectedItem() + "')");
         Object[][] b = getTableData(JTable);
         for (Object[] b1 : b) {
             String bb = "";
             for (int j = 0; j <= b1.length; j++) {
                 if (j == b1.length) {
                     bb += "'" + JTNoOpnameSPK.getText() + "'";
                 } else if ((j == b1.length - 1) || (j == b1.length - 2) || (j == b1.length - 5)) {
                     bb += "" + b1[j] + ",";
                 } else {
                     bb += "'" + b1[j] + "',";
                 }
             }
             list.add("INSERT INTO `tbdetailopnamespk`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`Status`,`NoOpnameSPK`) VALUES (" + bb + ")");
         }
         Object[][] c = getTableData(JTable1);

         for (int i = 0; i < c.length; i++) {
             String cc = "";
             for (int j = 0; j < c[i].length + 1; j++) {
                 if (j == c[i].length) {
                     cc += "'" + JTNoOpnameSPK.getText() + "'";
                 } else if ((j == c[i].length - 3) || (j == c[i].length - 6) || (j == c[i].length - 1)) {
                     cc += "" + c[i][j] + ",";
                 } else {
                     cc += "'" + c[i][j] + "',";
                 }
             }
             list.add("INSERT INTO `tbdetailopnamespk2`(`NoCol`, `KodeBarang`, `DeskripsiBarang`, `Jumlah`, `Satuan`,`Status`,`NoOpnameSPK`) VALUES (" + cc + ")");
         }
         RunMultiUpd runMultiUpd = new F.RunMultiUpd();
         runMultiUpd.setQuery(list);
         runMultiUpd.seterorm("Gagal Tambah Data !");
         int no = runMultiUpd.excute();
         if (no != 0) {
             showMessageDialog(this, "Berhasil Tambah Data");
             F.History.STambah("Tambah Data OSPK " + JTNoOpnameSPK.getText());
             F.VarJFrame.menuOpnameSPK.refresh();
             tambahOpnameSPK.dispose();
             tambahOpnameSPK = null;
             if (F.VarJFrame.tambahOpnameSPK == null) {
                 F.VarJFrame.tambahOpnameSPK = new TambahOSPK();
             }
         }          // TODO add your handling code here:
     }//GEN-LAST:event_jButton2ActionPerformed

     private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
     {//GEN-HEADEREND:event_jButton3ActionPerformed

         JTNoOpnameSPK.setText(GenNoStockOpname());
         List<String> list = new ArrayList<>();
         list.add("INSERT INTO `tbopnamespk`(`NoOpnameSPK`, `NoPerintahKerja`, `Tgl`, `Plat`, `Sopir`, `JPermintaan`, `JPekerjaan`, `TingkatPekerjaan`, `KMT`, `User`,`CatKhusus`,`KaMekanik`, `Mekanik`) VALUES ("
                 + "'" + JTNoOpnameSPK.getText() + "','" + JtNoPermintaanKerja.getSelectedItem().toString() + "','" + getstringfromdate(JdTGL.getDate(), "yyyy-MM-dd") + " " + JTTime.getText()
                 + "','" + JcPlat.getText() + "','" + JtSopir.getText() + "'," + JcPemintaan.getSelectedIndex()
                 + "," + JcPerbaikan.getSelectedIndex() + "," + JcPrioritas.getSelectedIndex()
                 + ",'" + JTKMMobil.getInt() + "','" + jtUser.getText() + "','" + JTCatatanKhusus.getText() + "','" + JcKaMekanik.getSelectedItem() + "','" + JcMekanik.getSelectedItem() + "')");
         Object[][] b = getTableData(JTable);
         for (Object[] b1 : b) {
             String bb = "";
             for (int j = 0; j <= b1.length; j++) {
                 if (j == b1.length) {
                     bb += "'" + JTNoOpnameSPK.getText() + "'";
                 } else if ((j == b1.length - 1) || (j == b1.length - 2) || (j == b1.length - 5)) {
                     bb += "" + b1[j] + ",";
                 } else {
                     bb += "'" + b1[j] + "',";
                 }
             }
             list.add("INSERT INTO `tbdetailopnamespk`(`NoCol`, `JenisPermintaan`, `Keterangan`, `Ongkos`,`Status`,`NoOpnameSPK`) VALUES (" + bb + ")");
         }
         Object[][] c = getTableData(JTable1);

         for (int i = 0; i < c.length; i++) {
             String cc = "";
             for (int j = 0; j < c[i].length + 1; j++) {
                 if (j == c[i].length) {
                     cc += "'" + JTNoOpnameSPK.getText() + "'";
                 } else if ((j == c[i].length - 3) || (j == c[i].length - 6) || (j == c[i].length - 1)) {
                     cc += "" + c[i][j] + ",";
                 } else {
                     cc += "'" + c[i][j] + "',";
                 }
             }
             list.add("INSERT INTO `tbdetailopnamespk2`(`NoCol`, `KodeBarang`, `DeskripsiBarang`, `Jumlah`, `Satuan`,`Status`,`NoOpnameSPK`) VALUES (" + cc + ")");
         }
         RunMultiUpd runMultiUpd = new F.RunMultiUpd();
         runMultiUpd.setQuery(list);
         runMultiUpd.seterorm("Gagal Tambah Data !");
         int no = runMultiUpd.excute();
         if (no != 0) {
             showMessageDialog(this, "Berhasil Tambah Data");
             F.History.STambah("Tambah Data OSPK " + JTNoOpnameSPK.getText());
             tambahOpnameSPK.dispose();
             tambahOpnameSPK = null;
             if (F.VarJFrame.tambahOpnameSPK == null) {
                 F.VarJFrame.tambahOpnameSPK = new TambahOSPK();
             }
             HashMap hashs = new HashMap();
             String Statusjcom;
             String StatusOrder;
             String Cari;
             hashs.put("Title", "OPNAME SPK");
             hashs.put("NoOpnameSPK", JTNoOpnameSPK.getText());
             hashs.put("KaMekanik", F.Variablebanking.Mechanik);
             hashs.put("Pimpinan", F.Variablebanking.Pimpinan);
             hashs.put("PrintedBy", "Di Print Oleh " + F.Variablebanking.SUsername + " Pada " + F.Datetostringwidthformat.getstringfromdate(new Date(), "dd/MM/yyyy HH:mm"));
             FLaporan fLaporan = new F.FLaporan();
             fLaporan.sethashmap(hashs);
             fLaporan.setfilename("OpnameSPK");
             fLaporan.setErorm("Gagal Menampilkan Laporan " + this.getTitle());
             fLaporan.excute();
             if (!"admin".equals(F.Variablebanking.Slevel)) {
                 RunUpd runUpd = new RunUpd();
                 runUpd.setQuery("UPDATE `tbopnamespk` SET `Print`='Yes' WHERE `NoOpnameSPK`='" + JTNoOpnameSPK.getText() + "'");
                 runUpd.excute();
             }
             F.VarJFrame.menuOpnameSPK.refresh();
         }
     }//GEN-LAST:event_jButton3ActionPerformed

     private void JcKaMekanikItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_JcKaMekanikItemStateChanged
     {//GEN-HEADEREND:event_JcKaMekanikItemStateChanged
         // TODO add your handling code here:
     }//GEN-LAST:event_JcKaMekanikItemStateChanged

     private void JcKaMekanikActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JcKaMekanikActionPerformed
     {//GEN-HEADEREND:event_JcKaMekanikActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_JcKaMekanikActionPerformed

     private void JcMekanikItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_JcMekanikItemStateChanged
     {//GEN-HEADEREND:event_JcMekanikItemStateChanged
         // TODO add your handling code here:
     }//GEN-LAST:event_JcMekanikItemStateChanged

     private void JcMekanikActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JcMekanikActionPerformed
     {//GEN-HEADEREND:event_JcMekanikActionPerformed
         // TODO add your handling code here:
     }//GEN-LAST:event_JcMekanikActionPerformed

     private void JcCariKaMekanikActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JcCariKaMekanikActionPerformed
     {//GEN-HEADEREND:event_JcCariKaMekanikActionPerformed
         JcKaMekanik.hidePopup();
         JcCariMekanik.requestFocus();     // TODO add your handling code here:
     }//GEN-LAST:event_JcCariKaMekanikActionPerformed

     private void JcCariKaMekanikKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JcCariKaMekanikKeyReleased
     {//GEN-HEADEREND:event_JcCariKaMekanikKeyReleased
         JcKaMekanik.setQuery("SELECT `Nama` FROM `tbkamekanik` WHERE Status = 0 and `Nama` Like '%" + JcCariKaMekanik.getText() + "%'");
         JcKaMekanik.setaawalkosong(false);
         JcKaMekanik.excute();
         JcKaMekanik.showPopup();// TODO add your handling code here:
     }//GEN-LAST:event_JcCariKaMekanikKeyReleased

     private void JcCariMekanikKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_JcCariMekanikKeyReleased
     {//GEN-HEADEREND:event_JcCariMekanikKeyReleased
         JcMekanik.setQuery("SELECT `Nama` FROM `tbmekanik` WHERE Status = 0 and `Nama` Like '%" + JcCariMekanik.getText() + "%'");
         JcMekanik.setaawalkosong(false);
         JcMekanik.excute();
         JcMekanik.showPopup();         // TODO add your handling code here:
     }//GEN-LAST:event_JcCariMekanikKeyReleased

     private void JcCariMekanikActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JcCariMekanikActionPerformed
     {//GEN-HEADEREND:event_JcCariMekanikActionPerformed
         if (!"".equals(JcCariMekanik.getText()) && JcMekanik.getSelectedIndex() == -1) {
             if (F.JackOptionpane.jackop("Apakah Anda Yakin Mau Menambah Data Mekanik")) {
                 RunUpd runupd = new RunUpd();
                 runupd.setQuery("INSERT INTO `tbmekanik`(`Nama`, `Status`) VALUES ('" + JcCariMekanik.getText() + "',0)");
                 int stu = runupd.excute();
                 if (stu != 0) {
                     JOptionPane.showMessageDialog(this, "berhasil Tambah Data Mekanik");
                 } else {
                     JOptionPane.showMessageDialog(this, "gagal Tambah Data Mekanik");
                 }
             } else {
                 JOptionPane.showMessageDialog(null, "batal Menambah Data");
             }
         } else {
             JcMekanik.hidePopup();
             JTable.requestFocus();
         }
     }//GEN-LAST:event_JcCariMekanikActionPerformed

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private F.JackTextField JTCatatanKhusus;
     private F.RibuanTextField JTKMMobil;
     private F.JackTextField JTNoOpnameSPK;
     private javax.swing.JFormattedTextField JTTime;
     private F.Jktable JTable;
     private F.Jktable JTable1;
     private F.JKTextfield JcCariKaMekanik;
     private F.JKTextfield JcCariMekanik;
     private F.JcomFromDb JcKaMekanik;
     private F.JcomFromDb JcMekanik;
     private F.JcomFromDb JcPemintaan;
     private F.JcomFromDb JcPerbaikan;
     private F.JackTextField JcPlat;
     private F.JcomFromDb JcPrioritas;
     private com.toedter.calendar.JDateChooser JdTGL;
     private F.JackTextField JtCariPermintaan;
     private F.JcomFromDb JtNoPermintaanKerja;
     private F.JackTextField JtSopir;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JButton jButton3;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel22;
     private javax.swing.JLabel jLabel23;
     private javax.swing.JLabel jLabel24;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JScrollPane jScrollPane3;
     private F.JackTextField jtUser;
     // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(TambahOSPK.class.getName());

}
