/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proses.XPMBAN;

import F.RunMultiUpd;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zeppr
 */
public class FormTambahMasterBan extends javax.swing.JFrame {

    /**
     * Creates new form FormTambahMasterBan
     */
    public FormTambahMasterBan() {
        initComponents();
        setTitle("Tambah Master Ban");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        JcPlat.excute();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlableF13 = new F.JlableF();
        jlableF12 = new F.JlableF();
        jlableF4 = new F.JlableF();
        JcPlat = new F.JcomFromDb();
        JCTypeTruck = new F.JcomFromDb();
        jlableF3 = new F.JlableF();
        jdateCF1 = new F.JdateCF();
        JtNoSeriLama = new F.JKTextfield();
        jlableF5 = new F.JlableF();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable = new F.Jktable();
        jbuttonF2 = new F.JbuttonF();
        jbuttonF3 = new F.JbuttonF();
        jbuttonF4 = new F.JbuttonF();
        jbuttonF5 = new F.JbuttonF();
        jlableF6 = new F.JlableF();
        JtCariPlat = new F.JackTextField();
        jlableF14 = new F.JlableF();
        JnJumlahBan = new F.JNumberTextField();
        jlableF7 = new F.JlableF();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlableF13.setText("Type Truck");

        jlableF12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlableF12.setText("Ban Digunakan");

        jlableF4.setText("Plat");

        JcPlat.setQuery("SELECT  `NoPolisi` From `ttruck` ");
        JcPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JcPlat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JcPlatKeyReleased(evt);
            }
        });

        JCTypeTruck.setEnabled(false);
        JCTypeTruck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlableF3.setText("No Seri Lama");

        jdateCF1.setDate(new Date());
        jdateCF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jdateCF1KeyReleased(evt);
            }
        });

        JtNoSeriLama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JtNoSeriLama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtNoSeriLamaKeyReleased(evt);
            }
        });

        jlableF5.setText("Tanggal");

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "NoSeriLama", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(JTable);
        if (JTable.getColumnModel().getColumnCount() > 0) {
            JTable.getColumnModel().getColumn(0).setResizable(false);
            JTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jbuttonF2.setText("Tambah");
        jbuttonF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF2ActionPerformed(evt);
            }
        });

        jbuttonF3.setText("Ubah");
        jbuttonF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF3ActionPerformed(evt);
            }
        });

        jbuttonF4.setText("Hapus");
        jbuttonF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF4ActionPerformed(evt);
            }
        });

        jbuttonF5.setText("Simpan");
        jbuttonF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonF5ActionPerformed(evt);
            }
        });

        jlableF6.setText("Cari");

        JtCariPlat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JtCariPlat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtCariPlatKeyReleased(evt);
            }
        });

        jlableF14.setText("Jumlah Ban");

        JnJumlahBan.setEnabled(false);
        JnJumlahBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlableF7.setText("Tambah Master Ban");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(JtCariPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JCTypeTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JnJumlahBan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlableF12, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlableF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(JtNoSeriLama, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jlableF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jdateCF1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbuttonF5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlableF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlableF7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlableF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlableF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(JtCariPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JcPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlableF13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCTypeTruck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlableF14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JnJumlahBan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jlableF12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlableF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtNoSeriLama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlableF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdateCF1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbuttonF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbuttonF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jbuttonF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuttonF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtCariPlatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtCariPlatKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
             JcPlat.setSelectedIndex(1);
             JcPlat.requestFocus();
        }else        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             JcPlat.hidePopup();
             JtNoSeriLama.requestFocus();
         } else {
            JcPlat.setQuery("SELECT `NoPolisi` FROM `ttruck` where `NoPolisi` like '%" + JtCariPlat.getText() + "%'");
            JcPlat.setaawalkosong(false);
            JcPlat.excute();
            JcPlat.showPopup();
         }
    }//GEN-LAST:event_JtCariPlatKeyReleased

    private void JtNoSeriLamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtNoSeriLamaKeyReleased
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             jdateCF1.requestFocus();
         }
    }//GEN-LAST:event_JtNoSeriLamaKeyReleased

    private void JcPlatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JcPlatKeyReleased
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             JtNoSeriLama.requestFocus();
         }
    }//GEN-LAST:event_JcPlatKeyReleased

    private void jdateCF1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdateCF1KeyReleased
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
   tambahtable();
         }
    }//GEN-LAST:event_jdateCF1KeyReleased

    private void jbuttonF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF2ActionPerformed

   tambahtable();
    }//GEN-LAST:event_jbuttonF2ActionPerformed

    private void jbuttonF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF3ActionPerformed

   ubahtable();
    }//GEN-LAST:event_jbuttonF3ActionPerformed

    private void jbuttonF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF4ActionPerformed
hapustable();
    }//GEN-LAST:event_jbuttonF4ActionPerformed

    private void jbuttonF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonF5ActionPerformed
        if (JTable.getRowCount() != 0) {
            List<String> list = new ArrayList<>();
            Object[][] b = getTableData(JTable);
            for (int i = 0; i < b.length; i++) {
                String bb = "";
                for (int j = 0; j < b[i].length + 1; j++) {
                    if (j == b[i].length) {
                        bb += "'" + JcPlat.getSelectedItem()+ "'";
                    } else if ((j == b[i].length - 3)) {
                        bb += "" + b[i][j] + ",";
                    } else {
                        bb += "'" + b[i][j] + "',";
                    }
                }
                list.add("INSERT INTO `tbmban`(`NoBan`, `NoSeriBan`, `Tanggal`,`Plat`) VALUES (" + bb + ")");
            }
            RunMultiUpd runMultiUpd = new F.RunMultiUpd();
            runMultiUpd.setQuery(list);
            runMultiUpd.seterorm("Gagal Tambah Data !");
            int no = runMultiUpd.excute();
            if (no != 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil di simpan !!");
                F.History.STambah("Tambah Masterbarang " + JcPlat.getSelectedItem());
               // F.VarJFrame.menuPermintaanBarang.refresh();
               // F.VarJFrame.tambahPermintaanBarang.dispose();
               //n  F.VarJFrame.tambahPermintaanBarang = null;
            }
        }
    }//GEN-LAST:event_jbuttonF5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTambahMasterBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTambahMasterBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTambahMasterBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTambahMasterBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTambahMasterBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private F.JcomFromDb JCTypeTruck;
    private F.Jktable JTable;
    private F.JcomFromDb JcPlat;
    private F.JNumberTextField JnJumlahBan;
    private F.JackTextField JtCariPlat;
    private F.JKTextfield JtNoSeriLama;
    private javax.swing.JScrollPane jScrollPane1;
    private F.JbuttonF jbuttonF2;
    private F.JbuttonF jbuttonF3;
    private F.JbuttonF jbuttonF4;
    private F.JbuttonF jbuttonF5;
    private F.JdateCF jdateCF1;
    private F.JlableF jlableF12;
    private F.JlableF jlableF13;
    private F.JlableF jlableF14;
    private F.JlableF jlableF3;
    private F.JlableF jlableF4;
    private F.JlableF jlableF5;
    private F.JlableF jlableF6;
    private F.JlableF jlableF7;
    // End of variables declaration//GEN-END:variables

    void tambahtable() {
        if (!"".equals(JtNoSeriLama.getText())) {
            DefaultTableModel model = (DefaultTableModel) JTable.getModel();
            model.addRow(new Object[]{JTable.getRowCount() + 1, JtNoSeriLama.getText(), jdateCF1.GetString()});
            JOptionPane.showMessageDialog(this, "Berhasil Tambah Data");
            RefreshJtable();
        } else {
            JOptionPane.showMessageDialog(null, "No Seri Harus Di Isi");
        }
        JtNoSeriLama.requestFocus();
    }

    void ubahtable() {
        if (JTable.getSelectedRow() != -1) {
            JTable.setValueAt(JtNoSeriLama.getText(), JTable.getSelectedRow(), 1);
            JTable.setValueAt(jdateCF1.GetString(), JTable.getSelectedRow(), 2);
            JOptionPane.showMessageDialog(this, "Berhasil Ubah Data");
            RefreshJtable();
        }
    }

    void hapustable() {
        if (JTable.getSelectedRow() != -1) {
            ((DefaultTableModel) JTable.getModel()).removeRow(JTable.getSelectedRow());
            for (int a = 0; a < JTable.getRowCount(); a++) {
                JTable.setValueAt(a + 1, a, 0);
            }
            JOptionPane.showMessageDialog(this, "Berhasil Hapus Data");
            RefreshJtable();
        }
    }
    void RefreshJtable() {
        JnJumlahBan.setInt(JTable.getRowCount());
        JTable.clearSelection();
        JtNoSeriLama.setText("");
        jdateCF1.setDate(new Date());
    }
    public Object[][] getTableData(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = dtm.getValueAt(i, j);
            }
        }
        return tableData;
    }
}
